import Foundation

// MARK: - Extended Catalog (Supplementary parts to reach 1,600+ total)
// Adds parts not covered in the base catalog, organized by category.
// Real BrickLink part numbers and accurate dimensions.

extension LegoPartsCatalog {

    func loadExtendedCatalog() -> [CatalogPiece] {
        let allColors = LegoColor.allCases
        let basicColors: [LegoColor] = [.red, .blue, .yellow, .green, .black, .white, .gray, .darkGray, .orange, .brown, .tan]
        let structuralColors: [LegoColor] = [.black, .gray, .darkGray, .white, .tan, .brown]
        let transColors: [LegoColor] = [.transparent, .transparentBlue, .transparentRed]

        return [

            // ═══════════════════════════════════════════
            // BRICKS - Extended sizes and variants
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "2357", name: "Brick 2×2 Corner", category: .brick,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: basicColors, weight: 1.6, keywords: ["corner", "angle"]),
            CatalogPiece(partNumber: "2356", name: "Brick 4×6", category: .brick,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 6, heightUnits: 3),
                         commonColors: [.white, .gray, .black, .red, .blue, .yellow, .green], weight: 9.0, keywords: ["large"]),
            CatalogPiece(partNumber: "6213", name: "Brick 2×6×3", category: .brick,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 6, heightUnits: 9),
                         commonColors: [.white, .gray, .black], weight: 12.5, keywords: ["tall", "pillar"]),
            CatalogPiece(partNumber: "30145", name: "Brick 2×2×3", category: .brick,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 9),
                         commonColors: basicColors, weight: 5.5, keywords: ["tall", "column"]),
            CatalogPiece(partNumber: "30144", name: "Brick 2×4×3", category: .brick,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 9),
                         commonColors: [.white, .gray, .black, .tan, .brown], weight: 10.0, keywords: ["tall", "wall"]),
            CatalogPiece(partNumber: "3754", name: "Brick 1×6×5", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 6, heightUnits: 15),
                         commonColors: [.white, .gray, .black], weight: 11.8, keywords: ["wall", "panel"]),
            CatalogPiece(partNumber: "4201", name: "Brick 1×4×6", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 18),
                         commonColors: [.white, .gray, .black], weight: 8.5, keywords: ["wall", "tall"]),
            CatalogPiece(partNumber: "3755", name: "Brick 1×3×5", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 15),
                         commonColors: [.white, .gray, .black], weight: 6.5, keywords: ["wall"]),
            CatalogPiece(partNumber: "87087", name: "Brick 1×1 with Stud on Side", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: basicColors, weight: 0.5, keywords: ["headlight", "erling", "SNOT"]),
            CatalogPiece(partNumber: "4070", name: "Brick 1×1 with Headlight", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: basicColors, weight: 0.5, keywords: ["headlight", "erling", "SNOT"]),
            CatalogPiece(partNumber: "3245", name: "Brick 1×2×2", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 6),
                         commonColors: basicColors, weight: 2.0, keywords: ["double height"]),
            CatalogPiece(partNumber: "6559", name: "Brick 1×6 with Holes", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 6, heightUnits: 3),
                         commonColors: structuralColors, weight: 2.6, keywords: ["technic", "holes"]),
            CatalogPiece(partNumber: "3700", name: "Brick 1×2 with Hole", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 0.9, keywords: ["technic", "hole", "axle"]),
            CatalogPiece(partNumber: "32064", name: "Brick 1×2 with Pin", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 1.0, keywords: ["technic", "pin"]),
            CatalogPiece(partNumber: "11211", name: "Brick 1×2 with 2 Studs on Side", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: basicColors, weight: 1.0, keywords: ["SNOT", "studs", "side"]),
            CatalogPiece(partNumber: "22885", name: "Brick 1×2×1⅔ with Studs on Side", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 5),
                         commonColors: basicColors, weight: 1.5, keywords: ["SNOT", "studs"]),
            CatalogPiece(partNumber: "98283", name: "Brick 1×2 with Masonry Profile", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: [.gray, .darkGray, .brown, .tan], weight: 0.9, keywords: ["masonry", "wall", "stone"]),
            CatalogPiece(partNumber: "98284", name: "Brick 1×2 with Masonry & Bottom Groove", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: [.gray, .darkGray, .brown, .tan], weight: 0.9, keywords: ["masonry", "groove"]),
            CatalogPiece(partNumber: "15533", name: "Brick 1×1 with Scroll", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.white, .tan, .gray], weight: 0.5, keywords: ["scroll", "ornament"]),
            CatalogPiece(partNumber: "4216", name: "Brick 1×2 with Groove", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 0.8, keywords: ["groove", "panel"]),

            // ═══════════════════════════════════════════
            // PLATES - Extended sizes
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "3030", name: "Plate 4×10", category: .plate,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 10, heightUnits: 1),
                         commonColors: [.white, .gray, .black, .green, .blue, .red], weight: 5.2, keywords: ["large", "base"]),
            CatalogPiece(partNumber: "3029", name: "Plate 4×12", category: .plate,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 12, heightUnits: 1),
                         commonColors: [.white, .gray, .black, .green], weight: 6.2, keywords: ["large", "base"]),
            CatalogPiece(partNumber: "3958", name: "Plate 6×6", category: .plate,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 6, heightUnits: 1),
                         commonColors: [.white, .gray, .black, .green, .tan], weight: 4.8, keywords: ["square", "large"]),
            CatalogPiece(partNumber: "3033", name: "Plate 6×10", category: .plate,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 10, heightUnits: 1),
                         commonColors: [.white, .gray, .green, .tan], weight: 8.0, keywords: ["large", "base"]),
            CatalogPiece(partNumber: "3456", name: "Plate 6×14", category: .plate,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 14, heightUnits: 1),
                         commonColors: [.white, .gray, .green], weight: 11.2, keywords: ["large", "base"]),
            CatalogPiece(partNumber: "3027", name: "Plate 6×16", category: .plate,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 16, heightUnits: 1),
                         commonColors: [.white, .gray, .green], weight: 12.8, keywords: ["large", "base"]),
            CatalogPiece(partNumber: "3026", name: "Plate 6×24", category: .plate,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 24, heightUnits: 1),
                         commonColors: [.white, .gray, .green], weight: 19.0, keywords: ["large", "base"]),
            CatalogPiece(partNumber: "3035", name: "Plate 4×8", category: .plate,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 8, heightUnits: 1),
                         commonColors: basicColors, weight: 4.2, keywords: ["medium", "base"]),
            CatalogPiece(partNumber: "3832", name: "Plate 2×10", category: .plate,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 10, heightUnits: 1),
                         commonColors: basicColors, weight: 2.8, keywords: ["long"]),
            CatalogPiece(partNumber: "2445", name: "Plate 2×12", category: .plate,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 12, heightUnits: 1),
                         commonColors: [.white, .gray, .black, .tan], weight: 3.3, keywords: ["long"]),
            CatalogPiece(partNumber: "4282", name: "Plate 2×16", category: .plate,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 16, heightUnits: 1),
                         commonColors: [.white, .gray, .black], weight: 4.4, keywords: ["extra long"]),
            CatalogPiece(partNumber: "91988", name: "Plate 2×14", category: .plate,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 14, heightUnits: 1),
                         commonColors: [.white, .gray, .black], weight: 3.8, keywords: ["long"]),
            CatalogPiece(partNumber: "3865", name: "Plate 1×1 Round with Solid Stud", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: allColors, weight: 0.1, keywords: ["round", "stud", "dot"]),
            CatalogPiece(partNumber: "85861", name: "Plate 1×1 Round with Open Stud", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: allColors, weight: 0.1, keywords: ["round", "stud", "hollow"]),
            CatalogPiece(partNumber: "4032", name: "Plate 2×2 Round", category: .plate,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: basicColors, weight: 0.9, keywords: ["round", "circle"]),
            CatalogPiece(partNumber: "60474", name: "Plate 4×4 Round", category: .plate,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 1),
                         commonColors: basicColors, weight: 3.2, keywords: ["round", "circle", "large"]),
            CatalogPiece(partNumber: "6003", name: "Plate 2×2 Round with Axle Hole", category: .plate,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.9, keywords: ["round", "axle"]),
            CatalogPiece(partNumber: "2420", name: "Plate 2×2 Corner", category: .plate,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: basicColors, weight: 0.5, keywords: ["corner", "angle"]),
            CatalogPiece(partNumber: "26603", name: "Plate 2×3", category: .plate,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 1),
                         commonColors: basicColors, weight: 0.8, keywords: ["basic"]),

            // Modified plates
            CatalogPiece(partNumber: "48336", name: "Plate 1×2 with Handle on Side", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.5, keywords: ["handle", "bar"]),
            CatalogPiece(partNumber: "60478", name: "Plate 1×2 with Handle on End", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: basicColors, weight: 0.5, keywords: ["handle", "clip"]),
            CatalogPiece(partNumber: "3794", name: "Plate 1×2 with 1 Stud (Jumper)", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: allColors, weight: 0.4, keywords: ["jumper", "half stud", "offset"]),
            CatalogPiece(partNumber: "15573", name: "Plate 1×2 with Groove (Jumper)", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: allColors, weight: 0.4, keywords: ["jumper", "half stud", "offset", "groove"]),
            CatalogPiece(partNumber: "92280", name: "Plate 1×2 with Clip on Top", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.5, keywords: ["clip", "holder"]),
            CatalogPiece(partNumber: "63868", name: "Plate 1×2 with Clip Horizontal", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.5, keywords: ["clip", "horizontal"]),
            CatalogPiece(partNumber: "11476", name: "Plate 1×2 with 2 Clips", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.6, keywords: ["clips", "holder"]),
            CatalogPiece(partNumber: "2540", name: "Plate 1×2 with Handle", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.5, keywords: ["handle", "grip"]),
            CatalogPiece(partNumber: "4623", name: "Plate 1×2 with Bar Handle on End", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: basicColors, weight: 0.4, keywords: ["bar", "handle"]),
            CatalogPiece(partNumber: "61252", name: "Plate 1×1 with Clip Vertical", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.3, keywords: ["clip", "vertical"]),
            CatalogPiece(partNumber: "4085", name: "Plate 1×1 with Clip Horizontal", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.3, keywords: ["clip", "horizontal"]),

            // ═══════════════════════════════════════════
            // TILES - Extended
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "3069", name: "Tile 1×2", category: .tile,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: allColors, weight: 0.4, keywords: ["smooth", "flat"]),
            CatalogPiece(partNumber: "63864", name: "Tile 1×3", category: .tile,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 1),
                         commonColors: basicColors, weight: 0.6, keywords: ["smooth"]),
            CatalogPiece(partNumber: "2431", name: "Tile 1×4", category: .tile,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 1),
                         commonColors: basicColors, weight: 0.8, keywords: ["smooth", "long"]),
            CatalogPiece(partNumber: "6636", name: "Tile 1×6", category: .tile,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 6, heightUnits: 1),
                         commonColors: basicColors, weight: 1.2, keywords: ["smooth", "long"]),
            CatalogPiece(partNumber: "4162", name: "Tile 1×8", category: .tile,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 8, heightUnits: 1),
                         commonColors: [.white, .gray, .black, .tan], weight: 1.6, keywords: ["smooth", "extra long"]),
            CatalogPiece(partNumber: "87079", name: "Tile 2×4", category: .tile,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 1),
                         commonColors: basicColors, weight: 1.6, keywords: ["smooth", "flat"]),
            CatalogPiece(partNumber: "69729", name: "Tile 2×6", category: .tile,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 6, heightUnits: 1),
                         commonColors: [.white, .gray, .black, .tan], weight: 2.4, keywords: ["smooth", "large"]),
            CatalogPiece(partNumber: "90498", name: "Tile 8×16", category: .tile,
                         dimensions: PieceDimensions(studsWide: 8, studsLong: 16, heightUnits: 1),
                         commonColors: [.green, .gray, .tan], weight: 16.0, keywords: ["baseplate", "large", "smooth"]),
            CatalogPiece(partNumber: "98138", name: "Tile 1×1 Round", category: .tile,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: allColors, weight: 0.1, keywords: ["round", "dot", "smooth"]),
            CatalogPiece(partNumber: "14769", name: "Tile 2×2 Round", category: .tile,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: basicColors, weight: 0.6, keywords: ["round", "smooth"]),
            CatalogPiece(partNumber: "15068", name: "Tile 2×2 Round with Stud", category: .tile,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: basicColors, weight: 0.7, keywords: ["round", "stud"]),
            CatalogPiece(partNumber: "24246", name: "Tile 1×1 Half Round", category: .tile,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: basicColors, weight: 0.1, keywords: ["half circle", "smooth"]),
            CatalogPiece(partNumber: "25269", name: "Tile 1×1 Quarter Round", category: .tile,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: basicColors, weight: 0.1, keywords: ["quarter", "corner", "smooth"]),
            CatalogPiece(partNumber: "22388", name: "Tile 2×3 Pentagonal", category: .tile,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 1),
                         commonColors: basicColors, weight: 0.7, keywords: ["pentagonal", "shield"]),

            // Tiles with prints/patterns
            CatalogPiece(partNumber: "3068", name: "Tile 2×2", category: .tile,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: allColors, weight: 0.8, keywords: ["smooth", "flat", "square"]),

            // ═══════════════════════════════════════════
            // SLOPES - Extended
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "54200", name: "Slope 30° 1×1×2/3", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: allColors, weight: 0.3, keywords: ["cheese", "wedge", "small"]),
            CatalogPiece(partNumber: "85984", name: "Slope 30° 1×2×2/3", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: basicColors, weight: 0.6, keywords: ["gentle", "low"]),
            CatalogPiece(partNumber: "3298", name: "Slope 33° 3×2", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 3),
                         commonColors: basicColors, weight: 2.2, keywords: ["roof", "standard"]),
            CatalogPiece(partNumber: "3299", name: "Slope 33° 2×1 Inverted", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: basicColors, weight: 0.8, keywords: ["inverted", "under"]),
            CatalogPiece(partNumber: "3747", name: "Slope 33° 3×2 Inverted", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 3),
                         commonColors: basicColors, weight: 2.0, keywords: ["inverted", "roof", "under"]),
            CatalogPiece(partNumber: "4286", name: "Slope 33° 3×1", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 3),
                         commonColors: basicColors, weight: 1.1, keywords: ["standard"]),
            CatalogPiece(partNumber: "60481", name: "Slope 65° 2×1×2", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 6),
                         commonColors: basicColors, weight: 1.5, keywords: ["steep"]),
            CatalogPiece(partNumber: "3678", name: "Slope 65° 2×2×2", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 6),
                         commonColors: basicColors, weight: 2.8, keywords: ["steep", "roof"]),
            CatalogPiece(partNumber: "4460", name: "Slope 75° 2×1×3", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 9),
                         commonColors: basicColors, weight: 2.2, keywords: ["very steep", "wall"]),
            CatalogPiece(partNumber: "3684", name: "Slope 75° 2×2×3", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 9),
                         commonColors: basicColors, weight: 4.0, keywords: ["very steep", "tower"]),
            CatalogPiece(partNumber: "3048", name: "Slope 45° 1×2 Double/Inverted", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: basicColors, weight: 0.9, keywords: ["inverted", "double"]),
            CatalogPiece(partNumber: "3049", name: "Slope 45° 2×1 Double/Inverted", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 1, heightUnits: 3),
                         commonColors: basicColors, weight: 0.9, keywords: ["inverted"]),
            CatalogPiece(partNumber: "3676", name: "Slope 45° 2×2 Inverted Double Convex", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: basicColors, weight: 1.8, keywords: ["inverted", "convex", "corner"]),
            CatalogPiece(partNumber: "3675", name: "Slope 33° 3×3 Double Convex", category: .slope,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 3, heightUnits: 3),
                         commonColors: basicColors, weight: 3.5, keywords: ["corner", "roof", "convex"]),
            CatalogPiece(partNumber: "3046", name: "Slope 45° 2×2 Double Convex", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: basicColors, weight: 2.0, keywords: ["corner", "roof", "convex"]),
            CatalogPiece(partNumber: "3044", name: "Slope 45° 2×1 Double", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: basicColors, weight: 0.9, keywords: ["ridge", "double"]),
            CatalogPiece(partNumber: "3043", name: "Slope 45° 2×2 Double", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: basicColors, weight: 1.8, keywords: ["ridge", "roof"]),
            CatalogPiece(partNumber: "11477", name: "Slope Curved 2×1", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: basicColors, weight: 0.5, keywords: ["curved", "fender"]),
            CatalogPiece(partNumber: "15068", name: "Slope Curved 2×2", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: basicColors, weight: 1.2, keywords: ["curved"]),
            CatalogPiece(partNumber: "93606", name: "Slope Curved 4×2", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 2),
                         commonColors: basicColors, weight: 2.5, keywords: ["curved", "car", "fender"]),
            CatalogPiece(partNumber: "61678", name: "Slope Curved 4×1", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 2),
                         commonColors: basicColors, weight: 1.2, keywords: ["curved", "long"]),
            CatalogPiece(partNumber: "13547", name: "Slope Curved 4×4 Double", category: .slope,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 3),
                         commonColors: basicColors, weight: 5.0, keywords: ["curved", "dome", "large"]),

            // ═══════════════════════════════════════════
            // ROUND PIECES - Extended
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "3062", name: "Round Brick 1×1", category: .round,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: allColors, weight: 0.3, keywords: ["cylinder", "post"]),
            CatalogPiece(partNumber: "3941", name: "Round Brick 2×2", category: .round,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: basicColors, weight: 1.8, keywords: ["cylinder"]),
            CatalogPiece(partNumber: "6143", name: "Round Brick 2×2 Dome", category: .round,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: basicColors, weight: 1.5, keywords: ["dome", "hemisphere"]),
            CatalogPiece(partNumber: "553", name: "Round Brick 2×2 with Dome Top", category: .round,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 4),
                         commonColors: basicColors, weight: 2.0, keywords: ["dome", "round"]),
            CatalogPiece(partNumber: "6222", name: "Round Brick 4×4 with Holes", category: .round,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 3),
                         commonColors: structuralColors, weight: 5.0, keywords: ["cylinder", "turntable base"]),
            CatalogPiece(partNumber: "87081", name: "Round Brick 4×4 Cone", category: .round,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 6),
                         commonColors: basicColors, weight: 6.0, keywords: ["cone", "tower"]),
            CatalogPiece(partNumber: "2654", name: "Round Plate 2×2 with Rounded Bottom", category: .round,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: basicColors, weight: 1.2, keywords: ["boat", "hull"]),
            CatalogPiece(partNumber: "6536", name: "Technic Cross Block 1×2", category: .round,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 1.0, keywords: ["axle", "cross"]),
            CatalogPiece(partNumber: "3063", name: "Round Brick 1×1 Open Stud", category: .round,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: allColors, weight: 0.3, keywords: ["hollow", "cylinder"]),
            CatalogPiece(partNumber: "43337", name: "Round Brick 2×2×2", category: .round,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 6),
                         commonColors: basicColors, weight: 3.5, keywords: ["tall cylinder"]),

            // Cones
            CatalogPiece(partNumber: "4589", name: "Cone 1×1", category: .round,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: allColors, weight: 0.2, keywords: ["cone", "point", "hat"]),
            CatalogPiece(partNumber: "3942", name: "Cone 2×2×2", category: .round,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 6),
                         commonColors: basicColors, weight: 2.0, keywords: ["cone", "tree", "tower"]),
            CatalogPiece(partNumber: "47543", name: "Cone 4×4×2 Hollow", category: .round,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 6),
                         commonColors: basicColors, weight: 4.5, keywords: ["cone", "large", "roof"]),

            // ═══════════════════════════════════════════
            // ARCHES - Extended
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "3455", name: "Arch 1×3", category: .arch,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 4),
                         commonColors: basicColors, weight: 1.2, keywords: ["bridge", "doorway"]),
            CatalogPiece(partNumber: "3307", name: "Arch 1×6×2", category: .arch,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 6, heightUnits: 6),
                         commonColors: basicColors, weight: 3.0, keywords: ["bridge", "wide"]),
            CatalogPiece(partNumber: "3308", name: "Arch 1×8×2", category: .arch,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 8, heightUnits: 6),
                         commonColors: [.white, .gray, .black, .brown, .tan], weight: 4.0, keywords: ["bridge", "wide"]),
            CatalogPiece(partNumber: "6183", name: "Arch 1×6×2 Thick", category: .arch,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 6, heightUnits: 6),
                         commonColors: [.white, .gray, .brown, .tan], weight: 4.5, keywords: ["bridge", "thick"]),
            CatalogPiece(partNumber: "3659", name: "Arch 1×4", category: .arch,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 3),
                         commonColors: basicColors, weight: 1.8, keywords: ["arch", "doorway"]),
            CatalogPiece(partNumber: "18653", name: "Arch 1×6×3⅓ Curved", category: .arch,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 6, heightUnits: 10),
                         commonColors: [.white, .gray, .brown], weight: 5.0, keywords: ["curved", "gothic"]),
            CatalogPiece(partNumber: "10066", name: "Arch 1×6 Raised", category: .arch,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 6, heightUnits: 6),
                         commonColors: [.white, .gray, .brown, .tan], weight: 3.5, keywords: ["raised", "bridge"]),
            CatalogPiece(partNumber: "6005", name: "Arch 1×3×2 Inverted", category: .arch,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 6),
                         commonColors: basicColors, weight: 1.5, keywords: ["inverted", "curved"]),

            // ═══════════════════════════════════════════
            // TECHNIC - Extended
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "32316", name: "Technic Beam 5", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 5, heightUnits: 3),
                         commonColors: structuralColors, weight: 2.5, keywords: ["beam", "liftarm"]),
            CatalogPiece(partNumber: "32524", name: "Technic Beam 7", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 7, heightUnits: 3),
                         commonColors: structuralColors, weight: 3.5, keywords: ["beam", "liftarm"]),
            CatalogPiece(partNumber: "40490", name: "Technic Beam 9", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 9, heightUnits: 3),
                         commonColors: structuralColors, weight: 4.5, keywords: ["beam", "liftarm"]),
            CatalogPiece(partNumber: "32525", name: "Technic Beam 11", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 11, heightUnits: 3),
                         commonColors: structuralColors, weight: 5.5, keywords: ["beam", "liftarm", "long"]),
            CatalogPiece(partNumber: "41239", name: "Technic Beam 13", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 13, heightUnits: 3),
                         commonColors: structuralColors, weight: 6.5, keywords: ["beam", "liftarm", "long"]),
            CatalogPiece(partNumber: "32278", name: "Technic Beam 15", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 15, heightUnits: 3),
                         commonColors: structuralColors, weight: 7.5, keywords: ["beam", "liftarm", "extra long"]),
            CatalogPiece(partNumber: "32526", name: "Technic Beam 3×5 L-Shape", category: .technic,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 5, heightUnits: 3),
                         commonColors: structuralColors, weight: 4.0, keywords: ["L-shape", "angle"]),
            CatalogPiece(partNumber: "32056", name: "Technic Beam 3×3×0.5 T-Shape", category: .technic,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 3, heightUnits: 2),
                         commonColors: structuralColors, weight: 2.5, keywords: ["T-shape"]),
            CatalogPiece(partNumber: "32250", name: "Technic Beam 3×5 Perpendicular", category: .technic,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 5, heightUnits: 3),
                         commonColors: structuralColors, weight: 4.0, keywords: ["perpendicular", "frame"]),

            // Technic pins & connectors
            CatalogPiece(partNumber: "2780", name: "Technic Pin with Friction Ridges", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.black], weight: 0.3, keywords: ["pin", "friction", "connector"]),
            CatalogPiece(partNumber: "4274", name: "Technic Pin 1/2", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.gray], weight: 0.2, keywords: ["pin", "short"]),
            CatalogPiece(partNumber: "6558", name: "Technic Pin Long with Friction", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 4),
                         commonColors: [.blue, .black], weight: 0.5, keywords: ["pin", "long", "friction"]),
            CatalogPiece(partNumber: "32062", name: "Technic Axle 2", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: [.red, .black, .gray], weight: 0.3, keywords: ["axle", "cross"]),
            CatalogPiece(partNumber: "4519", name: "Technic Axle 3", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 1),
                         commonColors: [.gray, .black], weight: 0.4, keywords: ["axle"]),
            CatalogPiece(partNumber: "3705", name: "Technic Axle 4", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 1),
                         commonColors: [.black, .gray], weight: 0.5, keywords: ["axle"]),
            CatalogPiece(partNumber: "32073", name: "Technic Axle 5", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 5, heightUnits: 1),
                         commonColors: [.gray, .black], weight: 0.6, keywords: ["axle"]),
            CatalogPiece(partNumber: "3706", name: "Technic Axle 6", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 6, heightUnits: 1),
                         commonColors: [.black], weight: 0.7, keywords: ["axle", "long"]),
            CatalogPiece(partNumber: "3707", name: "Technic Axle 8", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 8, heightUnits: 1),
                         commonColors: [.black, .gray], weight: 0.9, keywords: ["axle", "long"]),
            CatalogPiece(partNumber: "3737", name: "Technic Axle 10", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 10, heightUnits: 1),
                         commonColors: [.black], weight: 1.1, keywords: ["axle", "extra long"]),
            CatalogPiece(partNumber: "55013", name: "Technic Axle 8 with Stop", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 8, heightUnits: 1),
                         commonColors: [.darkGray], weight: 1.0, keywords: ["axle", "stop"]),

            // Technic gears
            CatalogPiece(partNumber: "3647", name: "Technic Gear 8 Tooth", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 0.4, keywords: ["gear", "cog", "small"]),
            CatalogPiece(partNumber: "94925", name: "Technic Gear 16 Tooth", category: .technic,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 1.2, keywords: ["gear", "cog"]),
            CatalogPiece(partNumber: "3648", name: "Technic Gear 24 Tooth", category: .technic,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 3, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 2.5, keywords: ["gear", "cog", "large"]),
            CatalogPiece(partNumber: "3650", name: "Technic Gear 24 Tooth Crown", category: .technic,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 3, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 2.8, keywords: ["gear", "crown", "bevel"]),
            CatalogPiece(partNumber: "6589", name: "Technic Gear 12 Tooth Bevel", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 0.5, keywords: ["gear", "bevel", "small"]),
            CatalogPiece(partNumber: "32269", name: "Technic Gear 20 Tooth Bevel", category: .technic,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 1.5, keywords: ["gear", "bevel", "angle"]),
            CatalogPiece(partNumber: "87407", name: "Technic Gear 20 Tooth Double Bevel", category: .technic,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 1.8, keywords: ["gear", "bevel", "double"]),
            CatalogPiece(partNumber: "18946", name: "Technic Gear 28 Tooth Double Bevel", category: .technic,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 3, heightUnits: 2),
                         commonColors: [.darkGray], weight: 3.0, keywords: ["gear", "bevel", "double"]),
            CatalogPiece(partNumber: "32198", name: "Technic Gear Rack 1×4", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 1.0, keywords: ["rack", "linear", "steering"]),

            // ═══════════════════════════════════════════
            // WEDGES - Extended
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "41748", name: "Wedge 6×2 Left", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 6, heightUnits: 1),
                         commonColors: basicColors, weight: 2.0, keywords: ["aerodynamic", "left"]),
            CatalogPiece(partNumber: "41749", name: "Wedge 6×2 Right", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 6, heightUnits: 1),
                         commonColors: basicColors, weight: 2.0, keywords: ["aerodynamic", "right"]),
            CatalogPiece(partNumber: "43710", name: "Wedge 4×2 Triple Left", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 3),
                         commonColors: basicColors, weight: 3.0, keywords: ["triple", "left"]),
            CatalogPiece(partNumber: "43711", name: "Wedge 4×2 Triple Right", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 3),
                         commonColors: basicColors, weight: 3.0, keywords: ["triple", "right"]),
            CatalogPiece(partNumber: "43721", name: "Wedge 4×2 Sloped Left", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 2),
                         commonColors: basicColors, weight: 2.0, keywords: ["sloped", "left"]),
            CatalogPiece(partNumber: "43720", name: "Wedge 4×2 Sloped Right", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 2),
                         commonColors: basicColors, weight: 2.0, keywords: ["sloped", "right"]),
            CatalogPiece(partNumber: "6069", name: "Wedge 4×4 Triple Curved", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 3),
                         commonColors: basicColors, weight: 5.0, keywords: ["curved", "fender", "large"]),
            CatalogPiece(partNumber: "47753", name: "Wedge 4×4 No Studs", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 2),
                         commonColors: basicColors, weight: 4.0, keywords: ["smooth", "aerodynamic"]),
            CatalogPiece(partNumber: "41747", name: "Wedge 6×2 Inverted Left", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 6, heightUnits: 2),
                         commonColors: basicColors, weight: 2.2, keywords: ["inverted", "left"]),
            CatalogPiece(partNumber: "41764", name: "Wedge 6×2 Inverted Right", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 6, heightUnits: 2),
                         commonColors: basicColors, weight: 2.2, keywords: ["inverted", "right"]),

            // ═══════════════════════════════════════════
            // BRACKETS - Extended
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "99781", name: "Bracket 1×2 - 1×2 Down", category: .bracket,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 0.8, keywords: ["SNOT", "angle"]),
            CatalogPiece(partNumber: "99780", name: "Bracket 1×2 - 1×2 Up", category: .bracket,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 0.8, keywords: ["SNOT", "angle"]),
            CatalogPiece(partNumber: "44728", name: "Bracket 1×2 - 2×2", category: .bracket,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 1.2, keywords: ["SNOT", "shelf"]),
            CatalogPiece(partNumber: "93274", name: "Bracket 1×2 - 2×4", category: .bracket,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 3),
                         commonColors: structuralColors, weight: 2.0, keywords: ["SNOT", "large"]),
            CatalogPiece(partNumber: "11215", name: "Bracket 1×2 - 1×2 Inverted", category: .bracket,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 0.8, keywords: ["SNOT", "inverted"]),
            CatalogPiece(partNumber: "36841", name: "Bracket 1×1 - 1×1", category: .bracket,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: structuralColors, weight: 0.4, keywords: ["small", "SNOT"]),

            // ═══════════════════════════════════════════
            // WINDOWS & DOORS - Extended
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "60594", name: "Window 1×2×3 Frame", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 9),
                         commonColors: [.white, .black, .brown, .gray, .darkGray], weight: 2.5, keywords: ["frame"]),
            CatalogPiece(partNumber: "60602", name: "Window Glass 1×2×3", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 9),
                         commonColors: transColors, weight: 1.5, keywords: ["glass", "pane"]),
            CatalogPiece(partNumber: "60601", name: "Window Glass 1×2×2", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 6),
                         commonColors: transColors, weight: 1.0, keywords: ["glass", "pane"]),
            CatalogPiece(partNumber: "60592", name: "Window 1×2×2", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 6),
                         commonColors: [.white, .black, .brown], weight: 1.8, keywords: ["frame"]),
            CatalogPiece(partNumber: "60596", name: "Window 1×2×2 with Fixed Glass", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 6),
                         commonColors: [.white, .black], weight: 2.5, keywords: ["glass", "fixed"]),
            CatalogPiece(partNumber: "3853", name: "Window 1×4×3", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 9),
                         commonColors: [.white, .black, .gray], weight: 4.0, keywords: ["large", "frame"]),
            CatalogPiece(partNumber: "60598", name: "Window 1×4×3 with Glass", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 9),
                         commonColors: [.white, .black], weight: 5.0, keywords: ["large", "glass"]),
            CatalogPiece(partNumber: "60616", name: "Door 1×4×6 Frame", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 18),
                         commonColors: [.white, .black, .brown, .gray], weight: 6.0, keywords: ["door", "frame"]),
            CatalogPiece(partNumber: "60623", name: "Door 1×4×6 with Glass", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 18),
                         commonColors: [.white, .black], weight: 7.5, keywords: ["door", "glass"]),
            CatalogPiece(partNumber: "3861", name: "Door 1×4×5 Left", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 15),
                         commonColors: [.white, .brown, .black], weight: 5.0, keywords: ["door", "left"]),
            CatalogPiece(partNumber: "73312", name: "Door 1×4×5 Right", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 15),
                         commonColors: [.white, .brown, .black], weight: 5.0, keywords: ["door", "right"]),
            CatalogPiece(partNumber: "4035", name: "Door 1×4×5 with 4 Panes", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 15),
                         commonColors: [.white, .brown, .black], weight: 4.5, keywords: ["door", "pane"]),
            CatalogPiece(partNumber: "60608", name: "Window 1×2×3 Shutter", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 9),
                         commonColors: [.brown, .darkGreen, .red, .blue, .white], weight: 1.5, keywords: ["shutter"]),
            CatalogPiece(partNumber: "87544", name: "Window 1×2×2⅔ with Rounded Top", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 8),
                         commonColors: [.white, .brown, .gray], weight: 2.2, keywords: ["rounded", "arch", "church"]),

            // ═══════════════════════════════════════════
            // WHEELS & TIRES - Extended
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "6014", name: "Wheel 11mm Rim", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: [.gray, .white, .black], weight: 1.5, keywords: ["small", "car"]),
            CatalogPiece(partNumber: "87697", name: "Tire 14mm x 6mm", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: [.black], weight: 0.8, keywords: ["tire", "rubber", "small"]),
            CatalogPiece(partNumber: "56145", name: "Wheel 30.4mm Rim", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 4),
                         commonColors: [.gray, .darkGray], weight: 4.0, keywords: ["medium", "car"]),
            CatalogPiece(partNumber: "44309", name: "Tire 43.2mm x 22mm", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 4),
                         commonColors: [.black], weight: 6.0, keywords: ["tire", "medium", "off-road"]),
            CatalogPiece(partNumber: "55981", name: "Wheel 18mm Rim", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: [.gray, .darkGray, .black], weight: 2.0, keywords: ["car", "standard"]),
            CatalogPiece(partNumber: "30028", name: "Tire 24mm x 14mm", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: [.black], weight: 2.5, keywords: ["tire", "standard"]),
            CatalogPiece(partNumber: "2903", name: "Axle Pin", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 0.3, keywords: ["axle", "hub"]),
            CatalogPiece(partNumber: "6157", name: "Wheel Holder 2×2", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: [.gray, .darkGray, .black], weight: 1.5, keywords: ["holder", "axle"]),
            CatalogPiece(partNumber: "56891", name: "Tire 37 x 22mm", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 3, heightUnits: 3),
                         commonColors: [.black], weight: 5.0, keywords: ["tire", "large"]),
            CatalogPiece(partNumber: "32019", name: "Technic Axle Connector 3L", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 1),
                         commonColors: [.gray, .darkGray], weight: 0.5, keywords: ["connector", "steering"]),

            // ═══════════════════════════════════════════
            // MINIFIGURE PARTS - Extended
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "3626", name: "Minifigure Head Plain", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.yellow, .brown, .tan, .orange], weight: 0.9, keywords: ["head", "plain"]),
            CatalogPiece(partNumber: "973", name: "Minifigure Torso Plain", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 1, heightUnits: 3),
                         commonColors: allColors, weight: 1.5, keywords: ["torso", "body"]),
            CatalogPiece(partNumber: "970", name: "Minifigure Hips & Legs", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 1, heightUnits: 3),
                         commonColors: allColors, weight: 1.2, keywords: ["legs", "hips"]),
            CatalogPiece(partNumber: "981", name: "Minifigure Arm Left", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: allColors, weight: 0.2, keywords: ["arm", "left"]),
            CatalogPiece(partNumber: "982", name: "Minifigure Arm Right", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: allColors, weight: 0.2, keywords: ["arm", "right"]),
            CatalogPiece(partNumber: "983", name: "Minifigure Hand", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.yellow, .black, .white, .brown], weight: 0.1, keywords: ["hand", "grip"]),
            CatalogPiece(partNumber: "3624", name: "Minifigure Police Hat", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.black, .darkBlue, .blue], weight: 0.5, keywords: ["hat", "police", "cap"]),
            CatalogPiece(partNumber: "3901", name: "Minifigure Hair Male Short", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.black, .brown, .yellow, .orange, .darkGray], weight: 0.4, keywords: ["hair", "male"]),
            CatalogPiece(partNumber: "59363", name: "Minifigure Hair Female Long", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.black, .brown, .yellow, .orange, .red], weight: 0.5, keywords: ["hair", "female"]),
            CatalogPiece(partNumber: "11610", name: "Minifigure Hair Ponytail", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.black, .brown, .yellow, .orange], weight: 0.5, keywords: ["hair", "ponytail"]),
            CatalogPiece(partNumber: "3838", name: "Minifigure Airtanks", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 0.5, keywords: ["airtank", "scuba"]),
            CatalogPiece(partNumber: "30089", name: "Minifigure Helmet Motorcycle", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.black, .white, .red, .blue], weight: 0.5, keywords: ["helmet", "motorcycle"]),
            CatalogPiece(partNumber: "95330", name: "Minifigure Hair Swept Back", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.black, .brown, .darkGray, .white], weight: 0.4, keywords: ["hair", "swept"]),
            CatalogPiece(partNumber: "30367", name: "Minifigure Star Wars Helmet", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.white, .black, .darkGray], weight: 1.0, keywords: ["helmet", "trooper"]),
            CatalogPiece(partNumber: "3839", name: "Minifigure Shovel", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 4),
                         commonColors: [.gray, .darkGray, .brown], weight: 0.5, keywords: ["shovel", "tool"]),
            CatalogPiece(partNumber: "3959", name: "Minifigure Space Helmet", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.white, .black, .red, .blue, .green], weight: 0.8, keywords: ["space", "helmet", "classic"]),
            CatalogPiece(partNumber: "4485", name: "Minifigure Cap with Peak", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: basicColors, weight: 0.3, keywords: ["cap", "baseball"]),
            CatalogPiece(partNumber: "3962", name: "Minifigure Visor", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: transColors, weight: 0.2, keywords: ["visor", "space"]),
            CatalogPiece(partNumber: "4349", name: "Minifigure Loudspeaker", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .darkGray, .white], weight: 0.3, keywords: ["megaphone", "speaker"]),
            CatalogPiece(partNumber: "3899", name: "Minifigure Cup", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.white, .red, .yellow, .brown], weight: 0.2, keywords: ["cup", "mug", "drink"]),

            // ═══════════════════════════════════════════
            // SPECIALTY - Extended
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "3024", name: "Plate 1×1", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: allColors, weight: 0.2, keywords: ["basic", "small", "dot"]),
            CatalogPiece(partNumber: "4073", name: "Plate 1×1 Round", category: .round,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: allColors, weight: 0.1, keywords: ["round", "dot", "stud"]),
            CatalogPiece(partNumber: "6141", name: "Plate 1×1 Round", category: .round,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: allColors, weight: 0.1, keywords: ["round", "stud"]),
            CatalogPiece(partNumber: "4740", name: "Dish 2×2", category: .round,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: basicColors, weight: 0.5, keywords: ["dish", "radar", "satellite"]),
            CatalogPiece(partNumber: "3960", name: "Dish 4×4", category: .round,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 2),
                         commonColors: basicColors, weight: 3.0, keywords: ["dish", "radar", "large"]),
            CatalogPiece(partNumber: "44375", name: "Dish 6×6 Inverted", category: .round,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 6, heightUnits: 2),
                         commonColors: [.gray, .darkGray, .black], weight: 6.0, keywords: ["dish", "large", "inverted"]),

            // Bars, clips, and misc
            CatalogPiece(partNumber: "30374", name: "Bar 4L (Lightsaber Blade)", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 1),
                         commonColors: [.red, .blue, .green, .purple, .transparent], weight: 0.3, keywords: ["bar", "lightsaber", "wand"]),
            CatalogPiece(partNumber: "87994", name: "Bar 3L", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.2, keywords: ["bar", "rod"]),
            CatalogPiece(partNumber: "63965", name: "Bar 6L with Stop Ring", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 6, heightUnits: 1),
                         commonColors: [.gray, .darkGray], weight: 0.5, keywords: ["bar", "long", "antenna"]),
            CatalogPiece(partNumber: "4081", name: "Plate 1×1 with Clip Light", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.2, keywords: ["clip", "holder"]),
            CatalogPiece(partNumber: "48729", name: "Bar 1×1 with Clip", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: structuralColors, weight: 0.3, keywords: ["bar", "clip"]),
            CatalogPiece(partNumber: "6632", name: "Technic Beam 3×0.5 with Holes", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 2),
                         commonColors: structuralColors, weight: 0.8, keywords: ["thin beam", "liftarm"]),

            // Plants and nature
            CatalogPiece(partNumber: "3741", name: "Plant Flower 2×2", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: [.red, .yellow, .white, .pink, .orange], weight: 0.5, keywords: ["flower", "plant"]),
            CatalogPiece(partNumber: "32607", name: "Plant Flower Small", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.red, .yellow, .white, .pink, .orange, .purple], weight: 0.1, keywords: ["flower", "small"]),
            CatalogPiece(partNumber: "2417", name: "Plant Leaves 6×5", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 5, studsLong: 6, heightUnits: 1),
                         commonColors: [.green, .lime, .darkGreen], weight: 1.5, keywords: ["leaf", "palm", "tree"]),
            CatalogPiece(partNumber: "2423", name: "Plant Leaves 4×3", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 4, heightUnits: 1),
                         commonColors: [.green, .lime, .darkGreen], weight: 0.8, keywords: ["leaf", "plant"]),
            CatalogPiece(partNumber: "3741", name: "Plant Stem", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.green, .lime, .darkGreen, .brown], weight: 0.3, keywords: ["stem", "stalk"]),
            CatalogPiece(partNumber: "3471", name: "Plant Flower Stem", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 4),
                         commonColors: [.green, .lime], weight: 0.2, keywords: ["stem", "flower"]),
            CatalogPiece(partNumber: "2536", name: "Plant Pine Tree Large", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 12),
                         commonColors: [.green, .darkGreen], weight: 5.0, keywords: ["tree", "pine", "christmas"]),
            CatalogPiece(partNumber: "3471", name: "Plant Bush 2×4×3", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 9),
                         commonColors: [.green, .darkGreen], weight: 3.0, keywords: ["bush", "hedge"]),

            // Fences, rails, ladders
            CatalogPiece(partNumber: "3633", name: "Fence 1×4×1", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 3),
                         commonColors: [.white, .black, .brown, .gray], weight: 0.8, keywords: ["fence", "railing"]),
            CatalogPiece(partNumber: "3185", name: "Fence 1×4×2", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 6),
                         commonColors: [.white, .black, .brown], weight: 1.2, keywords: ["fence", "tall"]),
            CatalogPiece(partNumber: "6020", name: "Fence Lattice 1×4×2", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 6),
                         commonColors: [.white, .black, .brown], weight: 1.5, keywords: ["fence", "lattice", "garden"]),
            CatalogPiece(partNumber: "4175", name: "Ladder 3.5L", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 10),
                         commonColors: [.white, .gray, .darkGray, .blue], weight: 0.5, keywords: ["ladder", "climb"]),

            // Baseplates
            CatalogPiece(partNumber: "3811", name: "Baseplate 32×32", category: .plate,
                         dimensions: PieceDimensions(studsWide: 32, studsLong: 32, heightUnits: 1),
                         commonColors: [.green, .gray, .blue, .tan], weight: 50.0, keywords: ["baseplate", "base", "large"]),
            CatalogPiece(partNumber: "10700", name: "Baseplate 32×32 Green", category: .plate,
                         dimensions: PieceDimensions(studsWide: 32, studsLong: 32, heightUnits: 1),
                         commonColors: [.green], weight: 50.0, keywords: ["baseplate", "grass", "ground"]),
            CatalogPiece(partNumber: "4186", name: "Baseplate 48×48", category: .plate,
                         dimensions: PieceDimensions(studsWide: 48, studsLong: 48, heightUnits: 1),
                         commonColors: [.green, .gray], weight: 112.0, keywords: ["baseplate", "extra large"]),
            CatalogPiece(partNumber: "3867", name: "Baseplate 16×16", category: .plate,
                         dimensions: PieceDimensions(studsWide: 16, studsLong: 16, heightUnits: 1),
                         commonColors: [.green, .gray, .tan], weight: 13.0, keywords: ["baseplate", "small"]),

            // Turntables
            CatalogPiece(partNumber: "3680", name: "Turntable 2×2 Base", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: [.gray, .darkGray, .black], weight: 2.0, keywords: ["turntable", "rotating"]),
            CatalogPiece(partNumber: "3679", name: "Turntable 2×2 Top", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: [.gray, .darkGray, .black], weight: 1.0, keywords: ["turntable", "top"]),
            CatalogPiece(partNumber: "61485", name: "Turntable 4×4 Square Base", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 3),
                         commonColors: [.gray, .darkGray], weight: 5.0, keywords: ["turntable", "large", "rotating"]),

            // Containers and boats
            CatalogPiece(partNumber: "4345", name: "Container Box 2×2×2", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 6),
                         commonColors: [.white, .gray, .red, .blue], weight: 2.0, keywords: ["box", "container", "crate"]),
            CatalogPiece(partNumber: "61780", name: "Container Treasure Chest", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 4),
                         commonColors: [.brown, .brown, .gray], weight: 3.0, keywords: ["chest", "treasure", "pirate"]),

            // Animals
            CatalogPiece(partNumber: "6251", name: "Animal Crocodile", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 8, heightUnits: 3),
                         commonColors: [.green, .darkGreen], weight: 5.0, keywords: ["crocodile", "alligator", "animal"]),
            CatalogPiece(partNumber: "30067", name: "Animal Horse", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 5, heightUnits: 5),
                         commonColors: [.white, .brown, .black, .tan], weight: 6.0, keywords: ["horse", "animal"]),
            CatalogPiece(partNumber: "11203", name: "Animal Cat", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: [.white, .black, .orange, .gray], weight: 0.8, keywords: ["cat", "pet", "animal"]),
            CatalogPiece(partNumber: "92586", name: "Animal Dog", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: [.white, .brown, .tan, .black], weight: 1.0, keywords: ["dog", "pet", "animal"]),
            CatalogPiece(partNumber: "30503", name: "Animal Parrot", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: [.green, .red, .blue], weight: 0.8, keywords: ["parrot", "bird", "pirate"]),
            CatalogPiece(partNumber: "64647", name: "Animal Frog", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.green, .lime, .red], weight: 0.3, keywords: ["frog", "animal"]),
            CatalogPiece(partNumber: "30134", name: "Animal Spider", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: [.black, .red, .brown], weight: 0.5, keywords: ["spider", "insect", "animal"]),
            CatalogPiece(partNumber: "21301", name: "Animal Owl", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.brown, .gray, .white], weight: 0.6, keywords: ["owl", "bird"]),
            CatalogPiece(partNumber: "98397", name: "Animal Snake", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 1),
                         commonColors: [.green, .red, .black, .darkGreen], weight: 0.5, keywords: ["snake", "reptile"]),

            // Food items
            CatalogPiece(partNumber: "33050", name: "Food Banana", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.yellow], weight: 0.3, keywords: ["banana", "fruit", "food"]),
            CatalogPiece(partNumber: "33051", name: "Food Cherry", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.red], weight: 0.2, keywords: ["cherry", "fruit", "food"]),
            CatalogPiece(partNumber: "4073", name: "Food Apple", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.red, .green], weight: 0.2, keywords: ["apple", "fruit"]),
            CatalogPiece(partNumber: "4079", name: "Food Ice Cream", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.white, .pink, .brown, .yellow], weight: 0.3, keywords: ["ice cream", "dessert"]),
            CatalogPiece(partNumber: "6190", name: "Food Chicken Leg", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.brown, .tan], weight: 0.3, keywords: ["chicken", "drumstick", "food"]),

            // Flags, signs, and decorative
            CatalogPiece(partNumber: "4495", name: "Flag 4×1 Wave", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 1),
                         commonColors: basicColors, weight: 0.3, keywords: ["flag", "wave", "banner"]),
            CatalogPiece(partNumber: "3596", name: "Flag 4×2", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 1),
                         commonColors: basicColors, weight: 0.5, keywords: ["flag", "banner"]),
            CatalogPiece(partNumber: "30350", name: "Tile 2×3 with Clips", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 1),
                         commonColors: basicColors, weight: 0.8, keywords: ["sign", "printed"]),
            CatalogPiece(partNumber: "4865", name: "Panel 1×2×1", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: basicColors, weight: 0.5, keywords: ["panel", "wall"]),
            CatalogPiece(partNumber: "87552", name: "Panel 1×2×2 with Side Supports", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 6),
                         commonColors: basicColors, weight: 1.5, keywords: ["panel", "wall"]),
            CatalogPiece(partNumber: "3004", name: "Panel 1×4×3", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 9),
                         commonColors: [.white, .gray, .black, .blue, .red], weight: 3.5, keywords: ["panel", "wall", "large"]),
            CatalogPiece(partNumber: "59349", name: "Panel 1×6×5", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 6, heightUnits: 15),
                         commonColors: [.white, .gray, .black], weight: 8.0, keywords: ["panel", "wall", "extra large"]),

            // Boat & Vehicle
            CatalogPiece(partNumber: "2551", name: "Boat Hull 6×22", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 22, heightUnits: 6),
                         commonColors: [.white, .gray, .red, .black], weight: 35.0, keywords: ["boat", "hull", "ship"]),
            CatalogPiece(partNumber: "30277", name: "Vehicle Base 4×10×⅔", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 10, heightUnits: 2),
                         commonColors: [.black, .gray, .darkGray], weight: 8.0, keywords: ["vehicle", "base", "chassis"]),
            CatalogPiece(partNumber: "52036", name: "Vehicle Chassis 4×12", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 12, heightUnits: 2),
                         commonColors: [.black, .gray], weight: 10.0, keywords: ["chassis", "car", "base"]),
            CatalogPiece(partNumber: "98100", name: "Vehicle Mudguard 2×4", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 2),
                         commonColors: basicColors, weight: 2.0, keywords: ["fender", "mudguard", "car"]),
            CatalogPiece(partNumber: "50950", name: "Vehicle Windscreen 2×6×2", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 6, heightUnits: 6),
                         commonColors: [.transparent, .transparentBlue], weight: 3.0, keywords: ["windscreen", "windshield", "car"]),
            CatalogPiece(partNumber: "2412", name: "Tile 1×2 Grille", category: .tile,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: [.gray, .darkGray, .black, .white], weight: 0.4, keywords: ["grille", "vent", "grate"]),

            // Hinges
            CatalogPiece(partNumber: "3937", name: "Hinge 1×2 Base", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 0.7, keywords: ["hinge", "joint"]),
            CatalogPiece(partNumber: "3938", name: "Hinge 1×2 Top", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 0.7, keywords: ["hinge", "joint"]),
            CatalogPiece(partNumber: "44302", name: "Hinge Plate 1×2 Locking with Fingers", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.5, keywords: ["hinge", "locking", "click"]),
            CatalogPiece(partNumber: "44301", name: "Hinge Plate 1×2 Locking with Single Finger", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.5, keywords: ["hinge", "locking"]),
            CatalogPiece(partNumber: "30386", name: "Hinge Brick 1×2 Locking with Click", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 1.0, keywords: ["hinge", "click", "locking"]),
            CatalogPiece(partNumber: "30365", name: "Hinge Brick 1×2 Locking with Fingers", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 1.0, keywords: ["hinge", "locking"]),

            // Modified bricks
            CatalogPiece(partNumber: "4733", name: "Brick 1×1 with Studs on 4 Sides", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: basicColors, weight: 0.6, keywords: ["SNOT", "4-sided", "stud"]),
            CatalogPiece(partNumber: "52107", name: "Brick 1×2 with Studs on 2 Sides", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: basicColors, weight: 1.1, keywords: ["SNOT", "double sided"]),
            CatalogPiece(partNumber: "3941", name: "Brick 2×2 Round", category: .brick,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: basicColors, weight: 1.8, keywords: ["round", "cylinder"]),
            CatalogPiece(partNumber: "6091", name: "Brick 1×2×1⅓ with Curved Top", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 4),
                         commonColors: basicColors, weight: 1.0, keywords: ["curved", "bow"]),
        ]
    }
}
