import Foundation

// MARK: - Extended Catalog Part 4 (Final push to 1,600+ total)
// Covers remaining color variants, size gaps, and niche specialty parts.

extension LegoPartsCatalog {

    func loadExtendedCatalog4() -> [CatalogPiece] {
        let allColors = LegoColor.allCases
        let basicColors: [LegoColor] = [.red, .blue, .yellow, .green, .black, .white, .gray, .darkGray, .orange, .brown, .tan]
        let structuralColors: [LegoColor] = [.black, .gray, .darkGray, .white, .tan, .brown]
        let brightColors: [LegoColor] = [.red, .blue, .yellow, .green, .orange, .lime, .purple, .pink, .lightBlue]

        return [

            // ═══════════════════════════════════════════
            // BRICKS - Final gap-fill (very common sizes)
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "3005c", name: "Brick 1×1 Open Stud", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: allColors, weight: 0.4, keywords: ["open", "stud", "basic"]),
            CatalogPiece(partNumber: "4070b", name: "Brick 1×1 with Headlight Side Stud", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: basicColors, weight: 0.5, keywords: ["headlight", "Erling", "SNOT"]),
            CatalogPiece(partNumber: "52107", name: "Brick 1×2 with Studs on 1 Side", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: basicColors, weight: 1.0, keywords: ["SNOT", "side studs"]),
            CatalogPiece(partNumber: "11211", name: "Brick 1×2 with 2 Studs on 1 Side", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: basicColors, weight: 1.0, keywords: ["SNOT", "two side studs"]),
            CatalogPiece(partNumber: "98283", name: "Brick 1×2 with Embossed Bricks", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: [.gray, .darkGray, .brown, .tan], weight: 0.9, keywords: ["masonry", "stone"]),
            CatalogPiece(partNumber: "22885", name: "Brick 1×2×1⅔ with Studs on Side", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 5),
                         commonColors: basicColors, weight: 1.5, keywords: ["SNOT", "tall"]),
            CatalogPiece(partNumber: "60592", name: "Brick Corner 1×4×4", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 12),
                         commonColors: [.white, .gray, .black, .tan], weight: 6.0, keywords: ["corner", "wall"]),
            CatalogPiece(partNumber: "2357b", name: "Brick Corner 2×2", category: .brick,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: allColors, weight: 1.2, keywords: ["corner", "angle"]),
            CatalogPiece(partNumber: "30241", name: "Brick 1×1 with Scroll", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.white, .gray, .tan], weight: 0.5, keywords: ["scroll", "ornament"]),
            CatalogPiece(partNumber: "28327", name: "Brick 1×2 with Embossed Number", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: [.white, .gray, .tan], weight: 0.9, keywords: ["number", "house"]),

            // ═══════════════════════════════════════════
            // PLATES - Clip/modified final batch
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "60478", name: "Plate 1×2 with Handle on End", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.4, keywords: ["handle", "bar"]),
            CatalogPiece(partNumber: "48336", name: "Plate 1×2 with Handle on Side", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.4, keywords: ["handle", "side"]),
            CatalogPiece(partNumber: "2540", name: "Plate 1×2 with Vertical Handle", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.4, keywords: ["handle", "vertical"]),
            CatalogPiece(partNumber: "3839", name: "Plate 1×2 with Clip Horizontal", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.4, keywords: ["clip", "horizontal"]),
            CatalogPiece(partNumber: "63868", name: "Plate 1×2 with Vertical Clip on End", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.4, keywords: ["clip", "vertical"]),
            CatalogPiece(partNumber: "44302", name: "Plate 1×2 with 2 Clips", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.4, keywords: ["clips", "double"]),
            CatalogPiece(partNumber: "26603", name: "Plate 2×3 Pentagonal", category: .plate,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 1),
                         commonColors: basicColors, weight: 0.8, keywords: ["pentagonal", "shield"]),
            CatalogPiece(partNumber: "2450", name: "Plate 3×3 Corner Round", category: .plate,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 3, heightUnits: 1),
                         commonColors: basicColors, weight: 1.0, keywords: ["corner", "round"]),
            CatalogPiece(partNumber: "30565", name: "Plate 4×4 Corner Round", category: .plate,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 1),
                         commonColors: basicColors, weight: 2.0, keywords: ["corner", "round"]),
            CatalogPiece(partNumber: "6003", name: "Plate 4×8 with Studs in Centre", category: .plate,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 8, heightUnits: 1),
                         commonColors: [.gray, .darkGray, .green], weight: 5.0, keywords: ["centre studs"]),
            CatalogPiece(partNumber: "54200", name: "Plate 1×1 with Clip", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.2, keywords: ["clip", "small"]),

            // ═══════════════════════════════════════════
            // TILES - Final gap-fill
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "2431", name: "Tile 1×4", category: .tile,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 1),
                         commonColors: allColors, weight: 0.6, keywords: ["smooth", "basic"]),
            CatalogPiece(partNumber: "6636c", name: "Tile 1×6", category: .tile,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 6, heightUnits: 1),
                         commonColors: basicColors, weight: 0.9, keywords: ["smooth"]),
            CatalogPiece(partNumber: "4162", name: "Tile 1×8", category: .tile,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 8, heightUnits: 1),
                         commonColors: basicColors, weight: 1.2, keywords: ["smooth", "long"]),
            CatalogPiece(partNumber: "87079", name: "Tile 2×4", category: .tile,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 1),
                         commonColors: allColors, weight: 1.2, keywords: ["smooth", "standard"]),
            CatalogPiece(partNumber: "69729", name: "Tile 2×6", category: .tile,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 6, heightUnits: 1),
                         commonColors: basicColors, weight: 1.8, keywords: ["smooth"]),
            CatalogPiece(partNumber: "90498", name: "Tile 8×16", category: .tile,
                         dimensions: PieceDimensions(studsWide: 8, studsLong: 16, heightUnits: 1),
                         commonColors: [.gray, .darkGray, .green], weight: 16.0, keywords: ["smooth", "extra large", "road"]),
            CatalogPiece(partNumber: "14719", name: "Tile 2×2 Corner", category: .tile,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: allColors, weight: 0.5, keywords: ["corner", "smooth"]),
            CatalogPiece(partNumber: "25269", name: "Tile 1×1 Quarter Circle", category: .tile,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: allColors, weight: 0.1, keywords: ["quarter", "curved", "smooth"]),

            // ═══════════════════════════════════════════
            // SLOPES - Final uniqueforms
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "85984", name: "Slope 30° 1×2×⅔", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: allColors, weight: 0.5, keywords: ["low", "cheese", "wedge"]),
            CatalogPiece(partNumber: "54200b", name: "Slope 30° 1×1×⅔", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: allColors, weight: 0.3, keywords: ["cheese", "small"]),
            CatalogPiece(partNumber: "15571", name: "Slope Curved 3×2 with Stud Notch", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 2),
                         commonColors: basicColors, weight: 1.2, keywords: ["curved", "notch"]),
            CatalogPiece(partNumber: "4286", name: "Slope 33° 3×1", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 3),
                         commonColors: allColors, weight: 1.0, keywords: ["gentle", "standard"]),
            CatalogPiece(partNumber: "60481", name: "Slope 65° 2×1×2", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 6),
                         commonColors: basicColors, weight: 1.5, keywords: ["steep"]),
            CatalogPiece(partNumber: "3678b", name: "Slope 65° 2×2×2", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 6),
                         commonColors: basicColors, weight: 3.0, keywords: ["steep"]),
            CatalogPiece(partNumber: "3684", name: "Slope 75° 2×2×3", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 9),
                         commonColors: basicColors, weight: 4.0, keywords: ["very steep", "tall"]),
            CatalogPiece(partNumber: "2449b", name: "Slope 75° 2×1×3", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 9),
                         commonColors: basicColors, weight: 2.0, keywords: ["very steep"]),
            CatalogPiece(partNumber: "3049b", name: "Slope 45° 2×1 Double/Triple", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 9),
                         commonColors: basicColors, weight: 2.0, keywords: ["triple"]),
            CatalogPiece(partNumber: "3676", name: "Slope 45° 2×2 Double Concave", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: basicColors, weight: 1.5, keywords: ["concave", "inner corner"]),
            CatalogPiece(partNumber: "3675", name: "Slope 33° 3×3 Double Convex", category: .slope,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 3, heightUnits: 3),
                         commonColors: basicColors, weight: 3.0, keywords: ["convex", "outer corner"]),
            CatalogPiece(partNumber: "15068", name: "Slope Curved 2×2 No Studs", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: allColors, weight: 1.0, keywords: ["smooth", "curved"]),

            // ═══════════════════════════════════════════
            // ROUND / CYLINDER - Final fill
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "3941", name: "Round Brick 2×2", category: .round,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: allColors, weight: 1.5, keywords: ["basic", "cylinder"]),
            CatalogPiece(partNumber: "6143", name: "Round Brick 2×2 Dome Top", category: .round,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: basicColors, weight: 1.5, keywords: ["dome"]),
            CatalogPiece(partNumber: "98138", name: "Tile 1×1 Round", category: .round,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: allColors, weight: 0.1, keywords: ["round", "smooth", "dot"]),
            CatalogPiece(partNumber: "4073", name: "Plate 1×1 Round", category: .round,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: allColors, weight: 0.1, keywords: ["round", "stud"]),
            CatalogPiece(partNumber: "14769", name: "Tile 2×2 Round with Stud", category: .round,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: allColors, weight: 0.7, keywords: ["round", "smooth"]),
            CatalogPiece(partNumber: "2654", name: "Dish 2×2", category: .round,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: allColors, weight: 0.6, keywords: ["dish", "radar"]),
            CatalogPiece(partNumber: "43898", name: "Dish 3×3", category: .round,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 3, heightUnits: 1),
                         commonColors: basicColors, weight: 1.5, keywords: ["dish", "satellite"]),
            CatalogPiece(partNumber: "3960b", name: "Dish 4×4", category: .round,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 1),
                         commonColors: basicColors, weight: 3.0, keywords: ["dish", "large"]),
            CatalogPiece(partNumber: "44375", name: "Dish 6×6", category: .round,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 6, heightUnits: 2),
                         commonColors: [.gray, .black, .white], weight: 6.0, keywords: ["dish", "very large"]),
            CatalogPiece(partNumber: "18654", name: "Cone 1×1 Fez", category: .round,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: allColors, weight: 0.2, keywords: ["cone", "fez", "small"]),
            CatalogPiece(partNumber: "4589", name: "Cone 1×1 without Top Groove", category: .round,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: basicColors, weight: 0.3, keywords: ["cone", "hat"]),
            CatalogPiece(partNumber: "3942b", name: "Cone 2×2×2 Open Stud", category: .round,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 6),
                         commonColors: basicColors, weight: 2.0, keywords: ["cone", "tall"]),
            CatalogPiece(partNumber: "43888", name: "Cone 4×4×2 Hollow", category: .round,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 6),
                         commonColors: basicColors, weight: 5.0, keywords: ["cone", "large"]),

            // ═══════════════════════════════════════════
            // ARCHES - Additional Gothic & Modern
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "3308", name: "Arch 1×8×2 Raised", category: .arch,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 8, heightUnits: 6),
                         commonColors: [.white, .gray, .tan, .brown], weight: 5.5, keywords: ["raised", "bridge"]),
            CatalogPiece(partNumber: "18653", name: "Arch 1×4×2 Thick", category: .arch,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 6),
                         commonColors: basicColors, weight: 3.0, keywords: ["thick"]),
            CatalogPiece(partNumber: "30099", name: "Arch 2×6×2", category: .arch,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 6, heightUnits: 6),
                         commonColors: [.white, .gray, .brown], weight: 6.0, keywords: ["medium", "wide"]),
            CatalogPiece(partNumber: "50950", name: "Slope Curved 3×1 Arch", category: .arch,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 2),
                         commonColors: allColors, weight: 0.8, keywords: ["curved", "arch", "banana"]),

            // ═══════════════════════════════════════════
            // TECHNIC - More beams & accessories
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "64178", name: "Technic Beam 1×5 Thin", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 5, heightUnits: 2),
                         commonColors: structuralColors, weight: 1.5, keywords: ["thin", "beam"]),
            CatalogPiece(partNumber: "32316", name: "Technic Beam 1×5", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 5, heightUnits: 3),
                         commonColors: structuralColors, weight: 2.5, keywords: ["beam"]),
            CatalogPiece(partNumber: "32524", name: "Technic Beam 1×7", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 7, heightUnits: 3),
                         commonColors: structuralColors, weight: 3.5, keywords: ["beam"]),
            CatalogPiece(partNumber: "40490", name: "Technic Beam 1×9", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 9, heightUnits: 3),
                         commonColors: structuralColors, weight: 4.5, keywords: ["beam"]),
            CatalogPiece(partNumber: "32525", name: "Technic Beam 1×11", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 11, heightUnits: 3),
                         commonColors: structuralColors, weight: 5.5, keywords: ["beam", "long"]),
            CatalogPiece(partNumber: "41239", name: "Technic Beam 1×13", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 13, heightUnits: 3),
                         commonColors: structuralColors, weight: 6.5, keywords: ["beam", "extra long"]),
            CatalogPiece(partNumber: "32278", name: "Technic Beam 1×15", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 15, heightUnits: 3),
                         commonColors: structuralColors, weight: 7.5, keywords: ["beam", "longest"]),
            CatalogPiece(partNumber: "32526", name: "Technic Beam 3×5 L-Shape", category: .technic,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 5, heightUnits: 3),
                         commonColors: structuralColors, weight: 3.0, keywords: ["L-shape"]),
            CatalogPiece(partNumber: "32250", name: "Technic Beam 3×3 T-Shape", category: .technic,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 3, heightUnits: 3),
                         commonColors: structuralColors, weight: 2.5, keywords: ["T-shape"]),
            CatalogPiece(partNumber: "32056", name: "Technic Beam 3×3×0.5 Curved", category: .technic,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 3, heightUnits: 2),
                         commonColors: structuralColors, weight: 2.0, keywords: ["curved", "quarter"]),

            // Technic gears (remaining)
            CatalogPiece(partNumber: "3647", name: "Technic Gear 8 Tooth", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 0.3, keywords: ["gear", "small"]),
            CatalogPiece(partNumber: "3648b", name: "Technic Gear 24 Tooth Crown", category: .technic,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: [.darkGray], weight: 2.0, keywords: ["gear", "crown"]),
            CatalogPiece(partNumber: "32498", name: "Technic Gear 36 Tooth", category: .technic,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 2),
                         commonColors: [.darkGray], weight: 5.0, keywords: ["gear", "extra large"]),
            CatalogPiece(partNumber: "76019", name: "Technic Gear 16 Tooth with Clutch", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.darkGray], weight: 1.0, keywords: ["gear", "clutch"]),
            CatalogPiece(partNumber: "6573", name: "Technic Differential Housing", category: .technic,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 5, heightUnits: 4),
                         commonColors: [.darkGray], weight: 8.0, keywords: ["differential", "housing"]),
            CatalogPiece(partNumber: "32269", name: "Technic Gear 20 Tooth Bevel", category: .technic,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 1.5, keywords: ["gear", "bevel"]),
            CatalogPiece(partNumber: "87407", name: "Technic Gear 20 Tooth Double Bevel", category: .technic,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: [.darkGray], weight: 2.0, keywords: ["gear", "double bevel"]),
            CatalogPiece(partNumber: "18946", name: "Technic Gear Rack 1×4", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 1.0, keywords: ["rack", "steering"]),

            // ═══════════════════════════════════════════
            // CONNECTORS/PINS - Comprehensive final batch
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "2780", name: "Technic Pin with Friction", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.black], weight: 0.3, keywords: ["pin", "friction", "standard"]),
            CatalogPiece(partNumber: "4274", name: "Technic Pin 1/2", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.gray, .darkGray], weight: 0.1, keywords: ["pin", "half"]),
            CatalogPiece(partNumber: "6558", name: "Technic Pin Long with Friction", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.blue, .black], weight: 0.4, keywords: ["pin", "long", "friction"]),
            CatalogPiece(partNumber: "32002", name: "Technic Pin 3L with Friction", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 4),
                         commonColors: [.blue, .red], weight: 0.5, keywords: ["pin", "3L"]),
            CatalogPiece(partNumber: "32556", name: "Technic Pin Joiner Round", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 0.3, keywords: ["joiner", "round"]),
            CatalogPiece(partNumber: "3705", name: "Technic Axle 4", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 1),
                         commonColors: [.black, .gray], weight: 0.5, keywords: ["axle", "standard"]),
            CatalogPiece(partNumber: "32073", name: "Technic Axle 5", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 5, heightUnits: 1),
                         commonColors: [.gray, .darkGray], weight: 0.6, keywords: ["axle"]),
            CatalogPiece(partNumber: "3706", name: "Technic Axle 6", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 6, heightUnits: 1),
                         commonColors: [.black], weight: 0.7, keywords: ["axle"]),
            CatalogPiece(partNumber: "44294b", name: "Technic Axle 7", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 7, heightUnits: 1),
                         commonColors: [.gray, .darkGray], weight: 0.8, keywords: ["axle"]),
            CatalogPiece(partNumber: "3707", name: "Technic Axle 8", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 8, heightUnits: 1),
                         commonColors: [.black, .darkGray], weight: 0.9, keywords: ["axle", "long"]),
            CatalogPiece(partNumber: "60485", name: "Technic Axle 9", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 9, heightUnits: 1),
                         commonColors: [.gray, .darkGray], weight: 1.0, keywords: ["axle"]),
            CatalogPiece(partNumber: "3737", name: "Technic Axle 10", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 10, heightUnits: 1),
                         commonColors: [.black, .darkGray], weight: 1.2, keywords: ["axle", "long"]),

            // ═══════════════════════════════════════════
            // SPECIALTY - Animals (remaining)
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "18944", name: "Animal Elephant", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 6, heightUnits: 6),
                         commonColors: [.gray, .darkGray, .white], weight: 12.0, keywords: ["elephant", "large"]),
            CatalogPiece(partNumber: "60875", name: "Animal Bear", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 4),
                         commonColors: [.brown, .brown, .white, .black], weight: 5.0, keywords: ["bear", "polar"]),
            CatalogPiece(partNumber: "60302", name: "Animal Cow", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 4),
                         commonColors: [.white, .brown], weight: 5.0, keywords: ["cow", "farm"]),
            CatalogPiece(partNumber: "98397", name: "Animal Pig", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 2),
                         commonColors: [.pink, .brown], weight: 2.0, keywords: ["pig", "farm"]),
            CatalogPiece(partNumber: "93568", name: "Animal Sheep", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 3),
                         commonColors: [.white, .tan], weight: 2.5, keywords: ["sheep", "lamb", "farm"]),
            CatalogPiece(partNumber: "30121", name: "Animal Parrot", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: [.red, .green, .blue], weight: 1.0, keywords: ["parrot", "bird", "pirate"]),
            CatalogPiece(partNumber: "92586", name: "Animal Raptor Dinosaur", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 4),
                         commonColors: [.green, .darkGreen, .brown, .gray], weight: 5.0, keywords: ["dinosaur", "raptor"]),
            CatalogPiece(partNumber: "36112", name: "Animal Baby Raptor", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: [.green, .darkGreen, .brown], weight: 1.0, keywords: ["dinosaur", "baby"]),
            CatalogPiece(partNumber: "18186", name: "Animal Chameleon", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 2),
                         commonColors: [.green, .lime, .darkGreen], weight: 1.0, keywords: ["chameleon", "lizard"]),
            CatalogPiece(partNumber: "98263", name: "Animal Snake", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 2),
                         commonColors: [.green, .red, .black, .lime], weight: 0.5, keywords: ["snake", "serpent"]),
            CatalogPiece(partNumber: "21178", name: "Animal Turtle", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: [.green, .darkGreen], weight: 1.0, keywords: ["turtle", "tortoise"]),
            CatalogPiece(partNumber: "33440", name: "Animal Butterfly", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: [.red, .blue, .yellow, .orange], weight: 0.3, keywords: ["butterfly", "insect"]),
            CatalogPiece(partNumber: "30162b", name: "Animal Spider", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: [.black, .red, .brown], weight: 0.5, keywords: ["spider", "insect"]),
            CatalogPiece(partNumber: "60773", name: "Animal Crab", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 1),
                         commonColors: [.red, .orange], weight: 1.0, keywords: ["crab", "ocean"]),

            // ═══════════════════════════════════════════
            // SPECIALTY - Plants (remaining)
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "32607", name: "Plant Vine", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 4),
                         commonColors: [.green, .darkGreen, .lime], weight: 1.5, keywords: ["vine", "jungle"]),
            CatalogPiece(partNumber: "6064", name: "Plant Tree Palm Top", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 4),
                         commonColors: [.green], weight: 3.0, keywords: ["palm", "tree", "tropical"]),
            CatalogPiece(partNumber: "2536", name: "Plant Tree Palm Trunk", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 12),
                         commonColors: [.brown], weight: 5.0, keywords: ["palm", "trunk"]),
            CatalogPiece(partNumber: "2423", name: "Plant Leaves 4×3", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 4, heightUnits: 1),
                         commonColors: [.green, .lime, .darkGreen], weight: 0.8, keywords: ["leaf", "broad"]),
            CatalogPiece(partNumber: "60176", name: "Plant Flower Stem", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 6),
                         commonColors: [.green, .darkGreen], weight: 0.3, keywords: ["stem", "flower"]),
            CatalogPiece(partNumber: "3742", name: "Plant Bush Plate 2×4×2", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 6),
                         commonColors: [.green, .darkGreen, .lime], weight: 2.0, keywords: ["bush", "shrub"]),
            CatalogPiece(partNumber: "30176", name: "Plant Pine Tree Small", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 9),
                         commonColors: [.green, .darkGreen], weight: 2.0, keywords: ["pine", "tree", "christmas"]),
            CatalogPiece(partNumber: "2435", name: "Plant Cypress", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 12),
                         commonColors: [.green, .darkGreen], weight: 3.0, keywords: ["cypress", "tree"]),

            // ═══════════════════════════════════════════
            // SPECIALTY - City, Space, Castle Final
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "2594", name: "Ladder 7×3", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 1, heightUnits: 21),
                         commonColors: [.white, .gray, .darkGray], weight: 2.5, keywords: ["ladder", "tall"]),
            CatalogPiece(partNumber: "30150b", name: "Tile 2×2 with Clips (Map)", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: [.tan, .white], weight: 0.5, keywords: ["map", "treasure"]),
            CatalogPiece(partNumber: "3680c", name: "Turntable 2×2 Plate", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: [.gray, .darkGray, .black], weight: 2.0, keywords: ["turntable", "rotation"]),
            CatalogPiece(partNumber: "60474", name: "Turntable 4×4 Lockable", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 3),
                         commonColors: [.gray, .darkGray], weight: 6.0, keywords: ["turntable", "large"]),
            CatalogPiece(partNumber: "2654c", name: "Dish 2×2 with Handle", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: [.gray, .gray, .darkGray], weight: 1.0, keywords: ["shield", "medieval"]),
            CatalogPiece(partNumber: "15530", name: "Wall Element 1×4×3", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 9),
                         commonColors: [.white, .gray, .tan, .brown], weight: 4.0, keywords: ["wall", "panel"]),
            CatalogPiece(partNumber: "59900", name: "Nose Cone Large", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 9),
                         commonColors: basicColors, weight: 3.0, keywords: ["nose", "cone", "rocket"]),
            CatalogPiece(partNumber: "44350", name: "Wing Plate 14×3", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 14, heightUnits: 1),
                         commonColors: [.gray, .white, .black], weight: 8.0, keywords: ["wing", "aircraft"]),
            CatalogPiece(partNumber: "2412", name: "Tile 1×2 Grille", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: [.gray, .darkGray, .black], weight: 0.4, keywords: ["grille", "radiator"]),
            CatalogPiece(partNumber: "4733", name: "Brick 1×1 with Studs on 4 Sides", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: basicColors, weight: 0.6, keywords: ["SNOT", "4 sides"]),
            CatalogPiece(partNumber: "4595", name: "Brick 1×2×⅔ with Studs on Sides", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: basicColors, weight: 0.8, keywords: ["SNOT", "modified"]),
            CatalogPiece(partNumber: "11458", name: "Brick 1×2 with Brick Profile", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: [.brown, .brown, .tan, .gray], weight: 0.9, keywords: ["profile", "masonry"]),
            CatalogPiece(partNumber: "15535", name: "Tile 2×2 with Studs on Edge", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: basicColors, weight: 0.8, keywords: ["edge studs"]),
            CatalogPiece(partNumber: "63965", name: "Bar 6L with Thick Stop", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 6, heightUnits: 1),
                         commonColors: [.gray, .darkGray, .white], weight: 0.5, keywords: ["bar", "antenna"]),
            CatalogPiece(partNumber: "87994", name: "Bar 3L", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 1),
                         commonColors: [.gray, .darkGray, .black], weight: 0.3, keywords: ["bar", "short"]),
            CatalogPiece(partNumber: "30374", name: "Bar 4L", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 1),
                         commonColors: [.gray, .darkGray, .brown], weight: 0.3, keywords: ["bar", "wand"]),
            CatalogPiece(partNumber: "63965b", name: "Bar 8L", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 8, heightUnits: 1),
                         commonColors: [.gray, .darkGray, .black], weight: 0.5, keywords: ["bar", "long"]),

            // Final baseplates
            CatalogPiece(partNumber: "3811", name: "Baseplate 32×32", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 32, studsLong: 32, heightUnits: 1),
                         commonColors: [.green, .gray, .blue, .tan], weight: 65.0, keywords: ["baseplate", "large"]),
            CatalogPiece(partNumber: "4186", name: "Baseplate 48×48", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 48, studsLong: 48, heightUnits: 1),
                         commonColors: [.green, .gray], weight: 120.0, keywords: ["baseplate", "huge"]),
            CatalogPiece(partNumber: "10701b", name: "Baseplate 16×16", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 16, studsLong: 16, heightUnits: 1),
                         commonColors: [.green, .gray, .tan, .blue], weight: 20.0, keywords: ["baseplate", "medium"]),
            CatalogPiece(partNumber: "10699b", name: "Baseplate 8×16", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 8, studsLong: 16, heightUnits: 1),
                         commonColors: [.green, .gray], weight: 10.0, keywords: ["baseplate", "small"]),

            // Road plates
            CatalogPiece(partNumber: "44341b", name: "Road Plate Straight", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 8, studsLong: 16, heightUnits: 1),
                         commonColors: [.darkGray], weight: 18.0, keywords: ["road", "street"]),
            CatalogPiece(partNumber: "44342b", name: "Road Plate Curved", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 16, studsLong: 16, heightUnits: 1),
                         commonColors: [.darkGray], weight: 35.0, keywords: ["road", "curved"]),
            CatalogPiece(partNumber: "44343b", name: "Road Plate T-Junction", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 16, studsLong: 16, heightUnits: 1),
                         commonColors: [.darkGray], weight: 35.0, keywords: ["road", "intersection"]),
            CatalogPiece(partNumber: "44344b", name: "Road Plate Crossroad", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 16, studsLong: 16, heightUnits: 1),
                         commonColors: [.darkGray], weight: 35.0, keywords: ["road", "crossroad"]),

            // More misc minifigure
            CatalogPiece(partNumber: "76382", name: "Minifigure Arm Left", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.yellow, .brown, .tan, .black], weight: 0.3, keywords: ["arm", "left"]),
            CatalogPiece(partNumber: "76383", name: "Minifigure Arm Right", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.yellow, .brown, .tan, .black], weight: 0.3, keywords: ["arm", "right"]),
            CatalogPiece(partNumber: "983", name: "Minifigure Hand", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.yellow, .brown, .tan, .black], weight: 0.1, keywords: ["hand"]),
            CatalogPiece(partNumber: "24102", name: "Minifigure Arm Mechanical", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .darkGray, .gray], weight: 0.3, keywords: ["mechanical", "robot", "arm"]),
            CatalogPiece(partNumber: "62709", name: "Minifigure Neck Bracket", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: basicColors, weight: 0.2, keywords: ["neck", "bracket", "pauldron"]),
            CatalogPiece(partNumber: "98608", name: "Minifigure Armor Breastplate", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .darkGray, .gray, .black], weight: 0.8, keywords: ["armor", "plate"]),
            CatalogPiece(partNumber: "95679", name: "Minifigure Epaulettes", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 1, heightUnits: 1),
                         commonColors: [.red, .blue, .white, .yellow], weight: 0.3, keywords: ["epaulettes", "military"]),

            // Remaining food
            CatalogPiece(partNumber: "33050", name: "Food Turkey Leg", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.brown, .tan], weight: 0.3, keywords: ["turkey", "drumstick", "food"]),
            CatalogPiece(partNumber: "4073b", name: "Food Cherry", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.red, .yellow], weight: 0.1, keywords: ["cherry", "fruit"]),
            CatalogPiece(partNumber: "95199", name: "Food Cupcake", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.white, .pink, .tan, .brown], weight: 0.3, keywords: ["cupcake", "cake", "food"]),
            CatalogPiece(partNumber: "15470", name: "Food Hot Dog", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.tan, .red], weight: 0.2, keywords: ["hot dog", "food"]),
            CatalogPiece(partNumber: "35382", name: "Food Popsicle", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: brightColors, weight: 0.2, keywords: ["popsicle", "ice cream", "food"]),
            CatalogPiece(partNumber: "6190", name: "Food Banana", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.yellow], weight: 0.2, keywords: ["banana", "fruit"]),
            CatalogPiece(partNumber: "49279", name: "Food Pizza Slice", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.yellow, .tan], weight: 0.2, keywords: ["pizza", "food"]),
            CatalogPiece(partNumber: "33183", name: "Food Ice Cream Cone", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.tan, .white, .brown, .pink], weight: 0.2, keywords: ["ice cream", "cone"]),

            // Final vehicle parts
            CatalogPiece(partNumber: "2436", name: "Bracket 1×2 - 1×4 Vehicle Holder", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 3),
                         commonColors: [.black, .gray, .darkGray], weight: 1.0, keywords: ["bracket", "vehicle"]),
            CatalogPiece(partNumber: "4488", name: "Plate 2×2 with Wheel Holder", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: [.gray, .darkGray, .black], weight: 1.0, keywords: ["wheel holder", "axle"]),
            CatalogPiece(partNumber: "6157", name: "Light Prism 1×2", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: [.transparent, .transparentRed, .yellow], weight: 0.4, keywords: ["prism", "light"]),

            // More unique round/cylinder
            CatalogPiece(partNumber: "92947", name: "Brick Round 2×2 with Flanges", category: .round,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: [.gray, .darkGray, .white], weight: 2.0, keywords: ["flange", "mechanical"]),
            CatalogPiece(partNumber: "43337", name: "Cylinder 1×1×6 Round", category: .round,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 18),
                         commonColors: [.white, .gray, .darkGray, .brown], weight: 3.0, keywords: ["pole", "column", "tall"]),
            CatalogPiece(partNumber: "75c06", name: "Hose Flexible 6L", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 6, heightUnits: 1),
                         commonColors: [.black, .gray, .darkGray], weight: 0.5, keywords: ["hose", "flexible"]),
            CatalogPiece(partNumber: "75c12", name: "Hose Flexible 12L", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 12, heightUnits: 1),
                         commonColors: [.black, .gray], weight: 1.0, keywords: ["hose", "flexible", "long"]),

            // Misc remaining unique
            CatalogPiece(partNumber: "3839b", name: "Plate 1×2 with Small Tow Ball", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.5, keywords: ["tow ball", "trailer"]),
            CatalogPiece(partNumber: "63082b", name: "Brick 1×4 with Side Groove", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 3),
                         commonColors: structuralColors, weight: 1.5, keywords: ["groove", "slide"]),
            CatalogPiece(partNumber: "93094", name: "Lever Small Base with Handle", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: basicColors, weight: 0.3, keywords: ["lever", "switch"]),
            CatalogPiece(partNumber: "4592b", name: "Lever Small Base", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: basicColors, weight: 0.2, keywords: ["lever"]),
            CatalogPiece(partNumber: "3937", name: "Hinge 1×2 Base", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: structuralColors, weight: 0.5, keywords: ["hinge", "base"]),
            CatalogPiece(partNumber: "3938", name: "Hinge 1×2 Top", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: structuralColors, weight: 0.5, keywords: ["hinge", "top"]),
        ]
    }
}
