import Foundation

// MARK: - Extended Catalog Part 2 (More parts to reach 1,600+ total)
// Additional BrickLink parts covering more sizes, variants, and specialty categories.

extension LegoPartsCatalog {

    func loadExtendedCatalog2() -> [CatalogPiece] {
        let allColors = LegoColor.allCases
        let basicColors: [LegoColor] = [.red, .blue, .yellow, .green, .black, .white, .gray, .darkGray, .orange, .brown, .tan]
        let structuralColors: [LegoColor] = [.black, .gray, .darkGray, .white, .tan, .brown]
        let transColors: [LegoColor] = [.transparent, .transparentBlue, .transparentRed]

        return [

            // ═══════════════════════════════════════════
            // BRICKS - Additional modified bricks
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "2877", name: "Brick 1×2 with Grille", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: basicColors, weight: 0.8, keywords: ["grille", "vent"]),
            CatalogPiece(partNumber: "30414", name: "Brick 1×4 with Studs on Side", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 3),
                         commonColors: basicColors, weight: 1.8, keywords: ["SNOT", "side studs"]),
            CatalogPiece(partNumber: "30237", name: "Brick 1×2 with Vertical Clip", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 0.9, keywords: ["clip", "holder"]),
            CatalogPiece(partNumber: "3622b", name: "Brick 1×3 with Bow", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 3),
                         commonColors: basicColors, weight: 1.3, keywords: ["bow", "curved"]),
            CatalogPiece(partNumber: "6188", name: "Brick 2×8×6", category: .brick,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 8, heightUnits: 18),
                         commonColors: [.white, .gray, .black], weight: 25.0, keywords: ["wall", "tall", "large"]),
            CatalogPiece(partNumber: "3007", name: "Brick 2×8", category: .brick,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 8, heightUnits: 3),
                         commonColors: basicColors, weight: 6.8, keywords: ["long", "basic"]),
            CatalogPiece(partNumber: "3006", name: "Brick 2×10", category: .brick,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 10, heightUnits: 3),
                         commonColors: [.white, .gray, .black], weight: 8.5, keywords: ["long"]),
            CatalogPiece(partNumber: "2464", name: "Brick 2×12", category: .brick,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 12, heightUnits: 3),
                         commonColors: [.white, .gray, .black], weight: 10.2, keywords: ["extra long"]),
            CatalogPiece(partNumber: "6061", name: "Brick 2×4 Sloped", category: .brick,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 3),
                         commonColors: basicColors, weight: 3.0, keywords: ["sloped", "wedge"]),
            CatalogPiece(partNumber: "2462", name: "Brick 1×1×5", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 15),
                         commonColors: basicColors, weight: 3.5, keywords: ["pillar", "column", "tall"]),

            // Log bricks
            CatalogPiece(partNumber: "30136", name: "Brick 1×2 Log", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: [.brown, .brown, .tan], weight: 1.0, keywords: ["log", "wood", "palisade"]),
            CatalogPiece(partNumber: "30137", name: "Brick 1×4 Log", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 3),
                         commonColors: [.brown, .brown, .tan], weight: 2.0, keywords: ["log", "wood"]),

            // ═══════════════════════════════════════════
            // PLATES - More modified plates
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "3176", name: "Plate 2×3 with Helicopter Rotor Holder", category: .plate,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 1),
                         commonColors: structuralColors, weight: 1.0, keywords: ["helicopter", "rotor"]),
            CatalogPiece(partNumber: "4510", name: "Plate 1×8 with Door Rail", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 8, heightUnits: 1),
                         commonColors: [.white, .gray, .black], weight: 1.8, keywords: ["door", "rail", "sliding"]),
            CatalogPiece(partNumber: "6636", name: "Plate 1×6", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 6, heightUnits: 1),
                         commonColors: basicColors, weight: 0.9, keywords: ["basic"]),
            CatalogPiece(partNumber: "3460", name: "Plate 1×8", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 8, heightUnits: 1),
                         commonColors: basicColors, weight: 1.2, keywords: ["long"]),
            CatalogPiece(partNumber: "4477", name: "Plate 1×10", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 10, heightUnits: 1),
                         commonColors: basicColors, weight: 1.5, keywords: ["long"]),
            CatalogPiece(partNumber: "60479", name: "Plate 1×12", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 12, heightUnits: 1),
                         commonColors: basicColors, weight: 1.8, keywords: ["long"]),
            CatalogPiece(partNumber: "3070", name: "Tile 1×1", category: .tile,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: allColors, weight: 0.2, keywords: ["smooth", "flat", "small"]),
            CatalogPiece(partNumber: "4150", name: "Tile 2×2 Round with Stud", category: .tile,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: basicColors, weight: 0.7, keywords: ["round", "stud"]),

            // Wing plates
            CatalogPiece(partNumber: "3933", name: "Plate 4×4 with 45° Corner", category: .plate,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 1),
                         commonColors: basicColors, weight: 2.5, keywords: ["corner", "angle", "wing"]),
            CatalogPiece(partNumber: "2419", name: "Plate 4×6 with Cutout", category: .plate,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 6, heightUnits: 1),
                         commonColors: [.white, .gray, .black, .tan], weight: 3.5, keywords: ["cutout"]),
            CatalogPiece(partNumber: "30503b", name: "Plate 4×4 Round Corner", category: .plate,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 1),
                         commonColors: basicColors, weight: 2.8, keywords: ["round", "corner"]),
            CatalogPiece(partNumber: "43719", name: "Wedge Plate 4×4", category: .plate,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 1),
                         commonColors: basicColors, weight: 2.5, keywords: ["wedge", "wing"]),
            CatalogPiece(partNumber: "51739", name: "Wedge Plate 2×4 Left", category: .plate,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 1),
                         commonColors: basicColors, weight: 1.2, keywords: ["wedge", "wing", "left"]),
            CatalogPiece(partNumber: "51740", name: "Wedge Plate 2×4 Right", category: .plate,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 1),
                         commonColors: basicColors, weight: 1.2, keywords: ["wedge", "wing", "right"]),
            CatalogPiece(partNumber: "22390", name: "Wedge Plate 3×6 Pentagonal Left", category: .plate,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 6, heightUnits: 1),
                         commonColors: basicColors, weight: 2.5, keywords: ["wedge", "wing", "aircraft"]),
            CatalogPiece(partNumber: "22391", name: "Wedge Plate 3×6 Pentagonal Right", category: .plate,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 6, heightUnits: 1),
                         commonColors: basicColors, weight: 2.5, keywords: ["wedge", "wing", "aircraft"]),

            // ═══════════════════════════════════════════
            // SLOPES - More curved slopes and inverted
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "50746", name: "Slope Curved 1×1×⅔", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: allColors, weight: 0.2, keywords: ["curved", "small", "mini"]),
            CatalogPiece(partNumber: "11478", name: "Slope Curved 2×1 Inverted", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: basicColors, weight: 0.5, keywords: ["curved", "inverted"]),
            CatalogPiece(partNumber: "93273", name: "Slope Curved 4×1 Double", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 3),
                         commonColors: basicColors, weight: 1.5, keywords: ["curved", "double", "arch"]),
            CatalogPiece(partNumber: "24201", name: "Slope Curved 2×1 Inverted", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: basicColors, weight: 0.5, keywords: ["curved", "inverted"]),
            CatalogPiece(partNumber: "88930", name: "Slope Curved 2×4×⅔ with 2 Studs", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 2),
                         commonColors: basicColors, weight: 2.0, keywords: ["curved", "mudguard"]),
            CatalogPiece(partNumber: "61068", name: "Slope Curved 2×4×1⅓ with 4 Studs", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 4),
                         commonColors: basicColors, weight: 2.5, keywords: ["curved", "fender"]),
            CatalogPiece(partNumber: "3040", name: "Slope 45° 2×1", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: allColors, weight: 0.9, keywords: ["standard", "roof"]),
            CatalogPiece(partNumber: "3041", name: "Slope 45° 2×4 Double", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 3),
                         commonColors: basicColors, weight: 3.5, keywords: ["double", "roof", "ridge"]),
            CatalogPiece(partNumber: "3042", name: "Slope 45° 2×3", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 3),
                         commonColors: basicColors, weight: 2.2, keywords: ["roof", "standard"]),
            CatalogPiece(partNumber: "4161", name: "Slope 33° 1×6×5", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 6, heightUnits: 15),
                         commonColors: [.gray, .black, .white], weight: 8.0, keywords: ["large", "ramp"]),
            CatalogPiece(partNumber: "60477", name: "Slope 18° 4×1", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 2),
                         commonColors: basicColors, weight: 0.8, keywords: ["gentle", "low"]),
            CatalogPiece(partNumber: "60219", name: "Slope 18° 4×2", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 2),
                         commonColors: basicColors, weight: 1.5, keywords: ["gentle", "ramp"]),
            CatalogPiece(partNumber: "47458", name: "Slope 18° 4×2 Convex", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 2),
                         commonColors: basicColors, weight: 1.5, keywords: ["gentle", "convex"]),
            CatalogPiece(partNumber: "98560", name: "Slope Curved 6×1", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 6, heightUnits: 2),
                         commonColors: basicColors, weight: 1.5, keywords: ["curved", "long"]),
            CatalogPiece(partNumber: "10187", name: "Slope Curved 6×2", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 6, heightUnits: 3),
                         commonColors: basicColors, weight: 3.5, keywords: ["curved", "large"]),
            CatalogPiece(partNumber: "2341", name: "Slope 45° 2×2 with Cutout", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: basicColors, weight: 1.5, keywords: ["cutout", "cockpit"]),

            // ═══════════════════════════════════════════
            // TECHNIC - More specialized parts
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "32140", name: "Technic Beam 2×4 L-Shape", category: .technic,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 3),
                         commonColors: structuralColors, weight: 3.0, keywords: ["L-shape", "angle"]),
            CatalogPiece(partNumber: "32009", name: "Technic Beam 1×11.5 Double Bent", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 11, heightUnits: 3),
                         commonColors: structuralColors, weight: 5.0, keywords: ["bent", "frame"]),
            CatalogPiece(partNumber: "41677", name: "Technic Beam 2", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 1.0, keywords: ["beam", "short"]),
            CatalogPiece(partNumber: "32523", name: "Technic Beam 3", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 3),
                         commonColors: structuralColors, weight: 1.5, keywords: ["beam"]),
            CatalogPiece(partNumber: "6629", name: "Technic Beam 4×0.5", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 2),
                         commonColors: structuralColors, weight: 1.0, keywords: ["thin", "beam"]),
            CatalogPiece(partNumber: "32271", name: "Technic Beam 1×2 with Axle Hole", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 1.0, keywords: ["axle", "connector"]),

            // Technic panels
            CatalogPiece(partNumber: "64681", name: "Technic Panel Plate 3×7", category: .technic,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 7, heightUnits: 1),
                         commonColors: basicColors, weight: 3.0, keywords: ["panel", "fairing"]),
            CatalogPiece(partNumber: "64683", name: "Technic Panel Plate 3×11", category: .technic,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 11, heightUnits: 1),
                         commonColors: basicColors, weight: 5.0, keywords: ["panel", "fairing", "large"]),
            CatalogPiece(partNumber: "44661", name: "Technic Panel 1×3", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 3),
                         commonColors: basicColors, weight: 1.5, keywords: ["panel", "small"]),
            CatalogPiece(partNumber: "61070", name: "Technic Panel 1×7", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 7, heightUnits: 3),
                         commonColors: basicColors, weight: 3.5, keywords: ["panel", "side"]),

            // Technic connectors
            CatalogPiece(partNumber: "48989", name: "Technic Pin Connector Toggle Joint", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 0.8, keywords: ["toggle", "joint"]),
            CatalogPiece(partNumber: "32184", name: "Technic Cross Block 1×3", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 3),
                         commonColors: [.gray, .darkGray, .white], weight: 1.5, keywords: ["cross block", "perpendicular"]),
            CatalogPiece(partNumber: "48496", name: "Technic Ball Joint", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 0.5, keywords: ["ball", "joint", "socket"]),
            CatalogPiece(partNumber: "32174", name: "Technic Ball Socket", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: [.gray, .darkGray], weight: 0.8, keywords: ["ball", "socket"]),
            CatalogPiece(partNumber: "57585", name: "Technic Pin Connector 3L with 2 Pins", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 2),
                         commonColors: [.gray, .darkGray, .black], weight: 0.7, keywords: ["pin", "connector"]),
            CatalogPiece(partNumber: "32039", name: "Technic Connector with Axle Hole", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.gray, .darkGray], weight: 0.5, keywords: ["connector", "axle"]),
            CatalogPiece(partNumber: "6536", name: "Technic Cross Block 2 Holes", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: [.gray, .darkGray], weight: 1.0, keywords: ["cross", "perpendicular"]),
            CatalogPiece(partNumber: "32291", name: "Technic Cross Block 3 Holes", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 3),
                         commonColors: [.gray, .darkGray], weight: 1.5, keywords: ["cross", "three holes"]),
            CatalogPiece(partNumber: "63869", name: "Technic Cross Block Fork 2×2", category: .connector,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: [.gray, .darkGray], weight: 1.2, keywords: ["fork", "steering"]),

            // Technic other
            CatalogPiece(partNumber: "32028", name: "Technic Plate 1×2 with Holes", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.4, keywords: ["plate", "holes"]),
            CatalogPiece(partNumber: "3709", name: "Technic Plate 2×4 with Holes", category: .technic,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 1),
                         commonColors: structuralColors, weight: 1.2, keywords: ["plate", "holes"]),
            CatalogPiece(partNumber: "32001", name: "Technic Brick 1×2 with Axle Hole", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 1.0, keywords: ["brick", "axle"]),
            CatalogPiece(partNumber: "32000", name: "Technic Brick 1×4 with Holes", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 3),
                         commonColors: structuralColors, weight: 2.0, keywords: ["brick", "holes"]),
            CatalogPiece(partNumber: "32034", name: "Technic Angle Connector #2", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: [.gray, .darkGray, .black], weight: 0.5, keywords: ["angle", "connector"]),
            CatalogPiece(partNumber: "32192", name: "Technic Angle Connector #4", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: [.gray, .darkGray, .black], weight: 0.6, keywords: ["angle", "135 degrees"]),

            // ═══════════════════════════════════════════
            // WEDGE BRICKS - Extended
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "6565", name: "Wedge 3×2 Left", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 3),
                         commonColors: basicColors, weight: 2.0, keywords: ["left", "angled"]),
            CatalogPiece(partNumber: "6564", name: "Wedge 3×2 Right", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 3),
                         commonColors: basicColors, weight: 2.0, keywords: ["right", "angled"]),
            CatalogPiece(partNumber: "41768", name: "Wedge 4×2 Left", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 3),
                         commonColors: basicColors, weight: 2.8, keywords: ["left"]),
            CatalogPiece(partNumber: "41769", name: "Wedge 4×2 Right", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 3),
                         commonColors: basicColors, weight: 2.8, keywords: ["right"]),
            CatalogPiece(partNumber: "90195", name: "Wedge 2×2 Facet", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: basicColors, weight: 1.0, keywords: ["facet", "diamond"]),
            CatalogPiece(partNumber: "47405", name: "Wedge 2×4 Curved Right", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 2),
                         commonColors: basicColors, weight: 2.0, keywords: ["curved", "right"]),
            CatalogPiece(partNumber: "47456", name: "Wedge 2×4 Curved Left", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 2),
                         commonColors: basicColors, weight: 2.0, keywords: ["curved", "left"]),

            // ═══════════════════════════════════════════
            // DOORS & WINDOWS - More variants
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "60607", name: "Window 1×2×3 Pane Thick", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 9),
                         commonColors: transColors, weight: 1.8, keywords: ["glass", "thick"]),
            CatalogPiece(partNumber: "4872", name: "Window 1×2×2⅔ Pane", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 8),
                         commonColors: transColors, weight: 1.5, keywords: ["glass", "pane"]),
            CatalogPiece(partNumber: "30179", name: "Door 1×4×6 Barred", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 18),
                         commonColors: [.black, .gray, .darkGray], weight: 5.5, keywords: ["door", "jail", "prison"]),
            CatalogPiece(partNumber: "60621", name: "Door 1×4×6 with 3 Panes", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 18),
                         commonColors: [.white, .black], weight: 6.5, keywords: ["door", "glass", "panes"]),
            CatalogPiece(partNumber: "3853b", name: "Window 1×4×3 with Glass", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 9),
                         commonColors: [.white, .black], weight: 5.0, keywords: ["large", "glass"]),
            CatalogPiece(partNumber: "3854", name: "Window 1×4×3 Lattice", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 9),
                         commonColors: [.white, .brown, .black], weight: 3.5, keywords: ["lattice", "medieval"]),

            // ═══════════════════════════════════════════
            // BRACKETS & MODIFIED - Extended
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "73825", name: "Bracket 1×1 - 1×1 Inverted", category: .bracket,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: structuralColors, weight: 0.4, keywords: ["SNOT", "small", "inverted"]),
            CatalogPiece(partNumber: "44728b", name: "Bracket 1×2 - 2×2 Up", category: .bracket,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 1.2, keywords: ["SNOT", "up"]),

            // ═══════════════════════════════════════════
            // CONNECTORS & HINGES - Extended
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "3149", name: "Hinge Plate 2×5", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 5, heightUnits: 1),
                         commonColors: structuralColors, weight: 1.5, keywords: ["hinge", "plate"]),
            CatalogPiece(partNumber: "44568", name: "Hinge Plate 1×4 with 2 Fingers on Side", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.8, keywords: ["hinge", "locking"]),
            CatalogPiece(partNumber: "60471", name: "Hinge Plate 1×2 with 3 Fingers on Side", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.6, keywords: ["hinge", "3 fingers"]),
            CatalogPiece(partNumber: "60470", name: "Hinge Plate 1×2 with 2 Fingers on End", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.5, keywords: ["hinge", "fingers"]),
            CatalogPiece(partNumber: "6134", name: "Hinge Brick 2×2 with Axle Hole", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 2.0, keywords: ["hinge", "axle", "turntable"]),

            // ═══════════════════════════════════════════
            // SPECIALTY - Boat, Train, Castle
            // ═══════════════════════════════════════════

            // Train
            CatalogPiece(partNumber: "2878", name: "Train Track Straight", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 16, heightUnits: 1),
                         commonColors: [.gray, .darkGray], weight: 12.0, keywords: ["train", "track", "rail"]),
            CatalogPiece(partNumber: "2867", name: "Train Track Curved", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 16, heightUnits: 1),
                         commonColors: [.gray, .darkGray], weight: 14.0, keywords: ["train", "track", "curved"]),
            CatalogPiece(partNumber: "53400", name: "Train Track Flexible", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 16, heightUnits: 1),
                         commonColors: [.darkGray], weight: 8.0, keywords: ["train", "track", "flexible"]),
            CatalogPiece(partNumber: "53401", name: "Train Track Switch Left", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 16, heightUnits: 1),
                         commonColors: [.darkGray], weight: 15.0, keywords: ["train", "switch", "left"]),
            CatalogPiece(partNumber: "53404", name: "Train Track Switch Right", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 16, heightUnits: 1),
                         commonColors: [.darkGray], weight: 15.0, keywords: ["train", "switch", "right"]),
            CatalogPiece(partNumber: "2871", name: "Train Buffer", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 3),
                         commonColors: [.red, .gray], weight: 3.0, keywords: ["train", "buffer", "end"]),
            CatalogPiece(partNumber: "2852", name: "Train Wheel Large", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 1, heightUnits: 3),
                         commonColors: [.gray, .darkGray], weight: 3.0, keywords: ["train", "wheel"]),

            // Castle / Medieval
            CatalogPiece(partNumber: "3479", name: "Turntable Dish 6×6", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 6, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 6.0, keywords: ["turntable", "castle"]),
            CatalogPiece(partNumber: "30246", name: "Brick 1×1 with Scroll Pattern", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.gray, .tan, .brown], weight: 0.5, keywords: ["ornament", "castle"]),

            // More animals
            CatalogPiece(partNumber: "60557", name: "Animal Shark", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 6, heightUnits: 3),
                         commonColors: [.gray, .darkGray, .white, .blue], weight: 5.0, keywords: ["shark", "ocean", "fish"]),
            CatalogPiece(partNumber: "6187", name: "Animal Dolphin", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 5, heightUnits: 2),
                         commonColors: [.blue, .gray], weight: 4.0, keywords: ["dolphin", "ocean", "animal"]),
            CatalogPiece(partNumber: "30135", name: "Animal Scorpion", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 2),
                         commonColors: [.black, .red, .brown], weight: 1.5, keywords: ["scorpion", "insect"]),
            CatalogPiece(partNumber: "4589b", name: "Animal Chicken", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: [.white, .brown, .tan], weight: 0.8, keywords: ["chicken", "hen", "farm"]),
            CatalogPiece(partNumber: "6253", name: "Animal Monkey", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: [.brown, .tan], weight: 1.0, keywords: ["monkey", "ape"]),
            CatalogPiece(partNumber: "64648", name: "Animal Bat", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: [.black, .brown], weight: 0.5, keywords: ["bat", "halloween"]),
            CatalogPiece(partNumber: "14696", name: "Animal Rabbit", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: [.white, .brown, .tan], weight: 0.8, keywords: ["rabbit", "bunny"]),
            CatalogPiece(partNumber: "98386", name: "Animal Fish", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 1),
                         commonColors: [.orange, .blue, .yellow, .red], weight: 0.5, keywords: ["fish", "ocean"]),
            CatalogPiece(partNumber: "30125", name: "Animal Octopus", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 3, heightUnits: 2),
                         commonColors: [.red, .purple, .black], weight: 3.0, keywords: ["octopus", "ocean"]),

            // Weapons
            CatalogPiece(partNumber: "3959b", name: "Minifigure Weapon Sword", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 4),
                         commonColors: [.gray, .darkGray, .gray], weight: 0.4, keywords: ["sword", "weapon", "knight"]),
            CatalogPiece(partNumber: "4497", name: "Minifigure Weapon Spear", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 6),
                         commonColors: [.brown, .gray, .darkGray], weight: 0.5, keywords: ["spear", "lance", "weapon"]),
            CatalogPiece(partNumber: "3838b", name: "Minifigure Weapon Axe", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.gray, .darkGray, .gray], weight: 0.5, keywords: ["axe", "weapon", "viking"]),
            CatalogPiece(partNumber: "30173", name: "Minifigure Weapon Shield Round", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: basicColors, weight: 1.0, keywords: ["shield", "round", "knight"]),
            CatalogPiece(partNumber: "3846", name: "Minifigure Weapon Shield Triangular", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 1),
                         commonColors: basicColors, weight: 1.0, keywords: ["shield", "triangular"]),
            CatalogPiece(partNumber: "57899", name: "Minifigure Weapon Katana", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 5),
                         commonColors: [.gray, .darkGray, .gray], weight: 0.4, keywords: ["katana", "ninja", "sword"]),
            CatalogPiece(partNumber: "15445", name: "Minifigure Weapon Bow", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 4),
                         commonColors: [.brown, .brown, .gray], weight: 0.8, keywords: ["bow", "arrow", "archery"]),

            // Tools
            CatalogPiece(partNumber: "4006", name: "Minifigure Tool Wrench", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 0.2, keywords: ["wrench", "tool", "mechanic"]),
            CatalogPiece(partNumber: "3837", name: "Minifigure Tool Screwdriver", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.blue, .red, .gray], weight: 0.2, keywords: ["screwdriver", "tool"]),
            CatalogPiece(partNumber: "6246", name: "Minifigure Tool Binoculars", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.black, .gray, .darkGray], weight: 0.3, keywords: ["binoculars", "scout"]),
            CatalogPiece(partNumber: "4360", name: "Minifigure Tool Camera", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.black, .gray], weight: 0.3, keywords: ["camera", "photographer"]),
            CatalogPiece(partNumber: "3899b", name: "Minifigure Tool Frying Pan", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.black, .gray, .darkGray], weight: 0.3, keywords: ["frying pan", "cook"]),

            // ═══════════════════════════════════════════
            // ADDITIONAL BRICKS by category
            // ═══════════════════════════════════════════

            // More size variants for common pieces
            CatalogPiece(partNumber: "3036", name: "Plate 6×8", category: .plate,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 8, heightUnits: 1),
                         commonColors: [.white, .gray, .black, .green, .tan], weight: 6.5, keywords: ["medium"]),
            CatalogPiece(partNumber: "3032", name: "Plate 4×6", category: .plate,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 6, heightUnits: 1),
                         commonColors: basicColors, weight: 3.5, keywords: ["medium"]),
            CatalogPiece(partNumber: "3031", name: "Plate 4×4", category: .plate,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 1),
                         commonColors: basicColors, weight: 2.5, keywords: ["square"]),
            CatalogPiece(partNumber: "3795", name: "Plate 2×6", category: .plate,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 6, heightUnits: 1),
                         commonColors: basicColors, weight: 1.6, keywords: ["medium"]),

            // Staircase, fence, lattice
            CatalogPiece(partNumber: "30134b", name: "Stairs 7×4×6", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 7, heightUnits: 18),
                         commonColors: [.gray, .darkGray, .brown, .tan], weight: 12.0, keywords: ["stairs", "staircase", "steps"]),
            CatalogPiece(partNumber: "30055", name: "Fence 1×4×2 Ornamental", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 6),
                         commonColors: [.white, .black, .brown, .gray], weight: 1.8, keywords: ["fence", "ornamental", "iron"]),
            CatalogPiece(partNumber: "92589", name: "Fence Spindled 4×4×2", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 6),
                         commonColors: [.white, .black, .brown], weight: 3.5, keywords: ["fence", "quarter circle"]),

            // Light and electric
            CatalogPiece(partNumber: "4773", name: "Light Brick 1×1", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.transparent, .transparentRed, .transparentBlue], weight: 0.5, keywords: ["light", "LED"]),
            CatalogPiece(partNumber: "58176", name: "Brick 1×1 with LED", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.transparent, .white], weight: 0.5, keywords: ["light", "LED", "electric"]),

            // Space themed
            CatalogPiece(partNumber: "30208", name: "Cylinder 2×4×4 Half", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 12),
                         commonColors: [.gray, .white, .transparentBlue], weight: 6.0, keywords: ["cylinder", "half", "space"]),
            CatalogPiece(partNumber: "85861b", name: "Plate 1×1 Round Transparent", category: .round,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: transColors, weight: 0.1, keywords: ["transparent", "light", "dot"]),
            CatalogPiece(partNumber: "6152", name: "Windscreen 2×6×2 Canopy", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 6, heightUnits: 6),
                         commonColors: [.transparent, .transparentBlue], weight: 4.0, keywords: ["canopy", "cockpit", "aircraft"]),
            CatalogPiece(partNumber: "30602", name: "Slope 45° 2×2 with Cockpit Print", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: [.transparent, .transparentBlue], weight: 2.0, keywords: ["cockpit", "slope"]),
            CatalogPiece(partNumber: "2654b", name: "Dish 2×2 Inverted", category: .round,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: basicColors, weight: 0.6, keywords: ["dish", "inverted", "radar"]),

            // Duplo-adjacent large pieces
            CatalogPiece(partNumber: "92438", name: "Brick Modified 8×8×6", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 8, studsLong: 8, heightUnits: 18),
                         commonColors: [.green, .gray, .brown], weight: 40.0, keywords: ["rock", "large", "landscape"]),
            CatalogPiece(partNumber: "52211", name: "Panel 10×10×6 Quarter Dome", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 10, studsLong: 10, heightUnits: 18),
                         commonColors: [.transparent, .transparentBlue, .gray], weight: 25.0, keywords: ["dome", "quarter", "space"]),
            CatalogPiece(partNumber: "2339", name: "Brick Arch 8×2×6", category: .arch,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 8, heightUnits: 18),
                         commonColors: [.white, .gray, .brown, .tan], weight: 12.0, keywords: ["arch", "large", "bridge"]),

            // More round / cylinder variants
            CatalogPiece(partNumber: "6259", name: "Cylinder Quarter 2×2×5", category: .round,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 15),
                         commonColors: basicColors, weight: 4.0, keywords: ["quarter", "cylinder", "column"]),
            CatalogPiece(partNumber: "92926", name: "Cylinder 2×4×2 with Cutout", category: .round,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 6),
                         commonColors: [.gray, .white, .black], weight: 4.0, keywords: ["cylinder", "cutout"]),
            CatalogPiece(partNumber: "18674", name: "Round Brick 1×1 Half", category: .round,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: allColors, weight: 0.2, keywords: ["half", "cylinder"]),

            // More tile sizes and shapes
            CatalogPiece(partNumber: "6881", name: "Tile 6×6 with Studs on Edges", category: .tile,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 6, heightUnits: 1),
                         commonColors: [.gray, .darkGray, .green], weight: 6.0, keywords: ["large", "road"]),
            CatalogPiece(partNumber: "48183", name: "Tile 2×2 with Groove", category: .tile,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: allColors, weight: 0.8, keywords: ["smooth", "groove"]),
            CatalogPiece(partNumber: "88646", name: "Tile 3×4", category: .tile,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 4, heightUnits: 1),
                         commonColors: basicColors, weight: 1.5, keywords: ["smooth", "flat"]),
            CatalogPiece(partNumber: "6934", name: "Tile 3×6", category: .tile,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 6, heightUnits: 1),
                         commonColors: [.white, .gray, .black], weight: 2.5, keywords: ["smooth", "large"]),

            // More wedge plates
            CatalogPiece(partNumber: "24307", name: "Wedge Plate 3×4 Left", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 4, heightUnits: 1),
                         commonColors: basicColors, weight: 1.5, keywords: ["wedge", "wing", "left"]),
            CatalogPiece(partNumber: "24299", name: "Wedge Plate 3×4 Right", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 4, heightUnits: 1),
                         commonColors: basicColors, weight: 1.5, keywords: ["wedge", "wing", "right"]),
            CatalogPiece(partNumber: "6239", name: "Wedge Plate 8×6 Left", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 8, heightUnits: 1),
                         commonColors: basicColors, weight: 6.0, keywords: ["large", "wing", "aircraft"]),
            CatalogPiece(partNumber: "6238", name: "Wedge Plate 8×6 Right", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 8, heightUnits: 1),
                         commonColors: basicColors, weight: 6.0, keywords: ["large", "wing", "aircraft"]),

            // More hinge / articulation
            CatalogPiece(partNumber: "48452", name: "Hinge Brick 1×2 with Vertical End", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 0.8, keywords: ["hinge", "vertical"]),
            CatalogPiece(partNumber: "47452", name: "Hinge Plate 2×2 Locking Thin", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.6, keywords: ["hinge", "thin", "locking"]),
            CatalogPiece(partNumber: "92582", name: "Hinge Brick 1×2 with Axle Hole", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 1.0, keywords: ["hinge", "axle"]),

            // ═══════════════════════════════════════════
            // MINIFIGURE ACCESSORIES - More
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "30350b", name: "Minifigure Tile 2×3 Sign", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 1),
                         commonColors: basicColors, weight: 0.8, keywords: ["sign", "shield"]),
            CatalogPiece(partNumber: "6246a", name: "Minifigure Binoculars Town", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.black, .darkGray], weight: 0.3, keywords: ["binoculars", "town"]),
            CatalogPiece(partNumber: "4528", name: "Minifigure Jetpack", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.gray, .darkGray, .white, .black], weight: 0.8, keywords: ["jetpack", "space"]),
            CatalogPiece(partNumber: "30151", name: "Minifigure Quiver", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.brown, .brown, .gray], weight: 0.4, keywords: ["quiver", "arrows"]),
            CatalogPiece(partNumber: "4736", name: "Minifigure Flippers", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: [.black, .blue, .lime], weight: 0.3, keywords: ["flippers", "swim", "scuba"]),
            CatalogPiece(partNumber: "92585", name: "Minifigure Cape Cloth", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: [.red, .black, .blue, .purple, .white], weight: 0.3, keywords: ["cape", "cloth", "hero"]),
            CatalogPiece(partNumber: "2524", name: "Minifigure Backpack Non-Opening", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: basicColors, weight: 0.3, keywords: ["backpack", "rucksack"]),
            CatalogPiece(partNumber: "95228", name: "Minifigure Hair Tousled", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.black, .brown, .yellow, .orange, .darkGray], weight: 0.4, keywords: ["hair", "messy"]),
            CatalogPiece(partNumber: "36293", name: "Minifigure Hair Bun", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.black, .brown, .yellow, .orange], weight: 0.4, keywords: ["hair", "bun"]),
            CatalogPiece(partNumber: "3629", name: "Minifigure Hair Female Bob", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.black, .brown, .yellow, .red], weight: 0.4, keywords: ["hair", "bob"]),
            CatalogPiece(partNumber: "98726", name: "Minifigure Hair Mohawk", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.black, .red, .purple, .orange], weight: 0.5, keywords: ["hair", "mohawk", "punk"]),

            // ═══════════════════════════════════════════
            // ADDITIONAL SPECIALTY
            // ═══════════════════════════════════════════

            // Treasure, containers
            CatalogPiece(partNumber: "30150", name: "Tile 2×2 with Clips (Treasure Map)", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: [.tan, .white], weight: 0.5, keywords: ["map", "scroll", "treasure"]),
            CatalogPiece(partNumber: "2489", name: "Container Barrel 2×2×2", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 6),
                         commonColors: [.brown, .brown, .gray, .green], weight: 2.5, keywords: ["barrel", "container"]),
            CatalogPiece(partNumber: "32028b", name: "Plate 1×2 with Rail", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.5, keywords: ["rail", "door"]),
            CatalogPiece(partNumber: "87580", name: "Plate 2×2 with Groove and 1 Stud", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: allColors, weight: 0.6, keywords: ["jumper", "offset"]),
            CatalogPiece(partNumber: "30063", name: "Vehicle Steering Wheel", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .darkGray, .black, .white], weight: 0.3, keywords: ["steering", "wheel", "car"]),
            CatalogPiece(partNumber: "4600", name: "Vehicle Stretcher", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 6, heightUnits: 2),
                         commonColors: [.white], weight: 2.0, keywords: ["stretcher", "hospital", "ambulance"]),
            CatalogPiece(partNumber: "4079b", name: "Minifigure Seat 2×2", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: basicColors, weight: 1.2, keywords: ["seat", "chair"]),
            CatalogPiece(partNumber: "2599", name: "Minifigure Seat Chair", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 6),
                         commonColors: [.brown, .brown, .white, .black], weight: 2.0, keywords: ["chair", "seat", "furniture"]),

            // Road and city
            CatalogPiece(partNumber: "44336", name: "Ramp 6×6×2", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 6, heightUnits: 6),
                         commonColors: [.gray, .darkGray], weight: 10.0, keywords: ["ramp", "road", "skate"]),
            CatalogPiece(partNumber: "6636b", name: "Plate 1×6 with Fence", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 6, heightUnits: 3),
                         commonColors: [.white, .black, .brown], weight: 1.5, keywords: ["fence", "rail", "barrier"]),
            CatalogPiece(partNumber: "4032b", name: "Plate 2×2 Round with Axle Hole", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.9, keywords: ["round", "axle"]),

            // Brackets continued
            CatalogPiece(partNumber: "28802", name: "Bracket 1×2 - 1×4 Down", category: .bracket,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 3),
                         commonColors: structuralColors, weight: 1.5, keywords: ["SNOT", "large"]),

            // More plates
            CatalogPiece(partNumber: "3022", name: "Plate 2×2", category: .plate,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: allColors, weight: 0.5, keywords: ["basic", "square"]),
            CatalogPiece(partNumber: "3021", name: "Plate 2×3", category: .plate,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 1),
                         commonColors: allColors, weight: 0.8, keywords: ["basic"]),
            CatalogPiece(partNumber: "3020", name: "Plate 2×4", category: .plate,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 1),
                         commonColors: allColors, weight: 1.0, keywords: ["basic", "standard"]),
            CatalogPiece(partNumber: "3023", name: "Plate 1×2", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: allColors, weight: 0.3, keywords: ["basic", "small"]),
            CatalogPiece(partNumber: "3710", name: "Plate 1×4", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 1),
                         commonColors: allColors, weight: 0.5, keywords: ["basic"]),
            CatalogPiece(partNumber: "3666", name: "Plate 1×6", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 6, heightUnits: 1),
                         commonColors: basicColors, weight: 0.9, keywords: ["basic"]),
            CatalogPiece(partNumber: "3034", name: "Plate 2×8", category: .plate,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 8, heightUnits: 1),
                         commonColors: basicColors, weight: 2.2, keywords: ["long"]),

            // More slopes
            CatalogPiece(partNumber: "3665", name: "Slope 45° 2×1 Inverted", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: basicColors, weight: 0.8, keywords: ["inverted"]),
            CatalogPiece(partNumber: "3660", name: "Slope 45° 2×2 Inverted", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: basicColors, weight: 1.5, keywords: ["inverted"]),
            CatalogPiece(partNumber: "3039", name: "Slope 45° 2×2", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: allColors, weight: 1.8, keywords: ["standard", "roof"]),
            CatalogPiece(partNumber: "3038", name: "Slope 45° 2×3", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 3),
                         commonColors: basicColors, weight: 2.5, keywords: ["roof"]),
            CatalogPiece(partNumber: "3037", name: "Slope 45° 2×4", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 3),
                         commonColors: basicColors, weight: 3.5, keywords: ["roof", "standard"]),
            CatalogPiece(partNumber: "4856", name: "Slope 45° 4×4 Double Inverted", category: .slope,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 3),
                         commonColors: basicColors, weight: 7.0, keywords: ["inverted", "large"]),
            CatalogPiece(partNumber: "3297", name: "Slope 33° 1×3", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 3),
                         commonColors: basicColors, weight: 1.0, keywords: ["gentle"]),

            // More round
            CatalogPiece(partNumber: "6143b", name: "Dome Brick 2×2 Truncated", category: .round,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: basicColors, weight: 1.0, keywords: ["dome", "truncated"]),
            CatalogPiece(partNumber: "30367b", name: "Cylinder 2×2×2", category: .round,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 6),
                         commonColors: basicColors, weight: 3.5, keywords: ["cylinder", "tall"]),
            CatalogPiece(partNumber: "79757", name: "Cylinder 3×3×2", category: .round,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 3, heightUnits: 6),
                         commonColors: [.gray, .darkGray, .white], weight: 5.0, keywords: ["cylinder"]),

            // Technic motors / pneumatics placeholders
            CatalogPiece(partNumber: "2986", name: "Technic Motor 9V", category: .technic,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 8, heightUnits: 6),
                         commonColors: [.gray, .darkGray, .black], weight: 40.0, keywords: ["motor", "electric", "power"]),
            CatalogPiece(partNumber: "32693", name: "Technic Axle 12", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 12, heightUnits: 1),
                         commonColors: [.black], weight: 1.4, keywords: ["axle", "extra long"]),
            CatalogPiece(partNumber: "44294", name: "Technic Axle 7", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 7, heightUnits: 1),
                         commonColors: [.gray, .black], weight: 0.8, keywords: ["axle"]),
            CatalogPiece(partNumber: "32209", name: "Technic Axle 5.5 with Stop", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 5, heightUnits: 1),
                         commonColors: [.darkGray], weight: 0.7, keywords: ["axle", "stop"]),
            CatalogPiece(partNumber: "3749", name: "Technic Axle Pin", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 0.3, keywords: ["axle", "pin"]),
            CatalogPiece(partNumber: "43093", name: "Technic Axle Pin with Friction", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.blue, .black], weight: 0.3, keywords: ["axle", "pin", "friction"]),
            CatalogPiece(partNumber: "6553", name: "Technic Pole Reverser Handle", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 3),
                         commonColors: [.red, .blue, .gray], weight: 0.8, keywords: ["handle", "reverser"]),
            CatalogPiece(partNumber: "32054", name: "Technic Pin Long", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.black, .blue, .red], weight: 0.4, keywords: ["pin", "long"]),
            CatalogPiece(partNumber: "18651", name: "Technic Axle with Ball Joint", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 0.5, keywords: ["axle", "ball", "joint"]),

            // More window glass
            CatalogPiece(partNumber: "60603", name: "Window Glass 1×4×3", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 9),
                         commonColors: transColors, weight: 2.5, keywords: ["glass", "large"]),
            CatalogPiece(partNumber: "57895", name: "Window Glass 1×4×6", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 18),
                         commonColors: transColors, weight: 4.0, keywords: ["glass", "door", "large"]),

            // Garage doors & shutters
            CatalogPiece(partNumber: "4218", name: "Garage Roller Door 1×4×6", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 18),
                         commonColors: [.white, .gray, .darkGray], weight: 6.0, keywords: ["garage", "roller", "door"]),
            CatalogPiece(partNumber: "4219", name: "Garage Door Frame 1×4×6", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 18),
                         commonColors: [.white, .gray, .darkGray], weight: 5.0, keywords: ["garage", "frame"]),

            // Pneumatic / control
            CatalogPiece(partNumber: "47170", name: "Technic Shock Absorber 6.5L", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 6, heightUnits: 2),
                         commonColors: [.yellow, .gray, .black], weight: 2.0, keywords: ["shock", "spring", "suspension"]),
            CatalogPiece(partNumber: "731", name: "Technic Shock Absorber Small", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 2),
                         commonColors: [.yellow, .gray], weight: 1.5, keywords: ["shock", "spring"]),
            CatalogPiece(partNumber: "2856", name: "Technic Engine", category: .technic,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 6),
                         commonColors: [.gray, .darkGray], weight: 8.0, keywords: ["engine", "motor", "piston"]),
            CatalogPiece(partNumber: "32072", name: "Technic Knob Gear 12 Tooth", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 0.5, keywords: ["gear", "knob", "small"]),
            CatalogPiece(partNumber: "76244", name: "Technic Gear 28 Tooth", category: .technic,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 3, heightUnits: 2),
                         commonColors: [.darkGray], weight: 3.5, keywords: ["gear", "large"]),
            CatalogPiece(partNumber: "32270", name: "Technic Gear 12 Tooth Double Bevel", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 0.6, keywords: ["gear", "bevel"]),

            // ═══════════════════════════════════════════
            // MORE BRICKS - Filling remaining categories
            // ═══════════════════════════════════════════

            // Additional arch variants
            CatalogPiece(partNumber: "4490", name: "Arch 1×3 Pointed", category: .arch,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 5),
                         commonColors: basicColors, weight: 1.5, keywords: ["pointed", "gothic"]),
            CatalogPiece(partNumber: "4743", name: "Arch 2×4×2 Triple", category: .arch,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 6),
                         commonColors: [.white, .gray, .brown], weight: 5.0, keywords: ["triple", "aqueduct"]),
            CatalogPiece(partNumber: "15254", name: "Arch 1×6×2 Medium Thick", category: .arch,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 6, heightUnits: 6),
                         commonColors: basicColors, weight: 3.5, keywords: ["bridge", "medium"]),
            CatalogPiece(partNumber: "6182", name: "Arch 1×4×2", category: .arch,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 6),
                         commonColors: basicColors, weight: 2.5, keywords: ["arch", "doorway"]),
            CatalogPiece(partNumber: "92950", name: "Arch 1×3×3", category: .arch,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 9),
                         commonColors: basicColors, weight: 3.0, keywords: ["tall", "arch"]),

            // Modified bricks
            CatalogPiece(partNumber: "4855", name: "Brick 1×4×3 with Window", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 9),
                         commonColors: [.white, .gray, .black, .brown], weight: 3.5, keywords: ["window", "wall"]),
            CatalogPiece(partNumber: "3245b", name: "Brick 1×2×2 with Inside Axle Holder", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 6),
                         commonColors: basicColors, weight: 2.2, keywords: ["axle", "holder"]),
            CatalogPiece(partNumber: "47763", name: "Brick 2×4×3 Half", category: .brick,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 9),
                         commonColors: [.white, .gray], weight: 7.0, keywords: ["half", "angled"]),
            CatalogPiece(partNumber: "3065", name: "Brick 1×2 without Bottom Tube", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: transColors, weight: 0.7, keywords: ["transparent", "smooth bottom"]),
            CatalogPiece(partNumber: "6091b", name: "Brick Curved 1×2×1⅓ with Top", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 4),
                         commonColors: basicColors, weight: 1.0, keywords: ["curved", "bow"]),
            CatalogPiece(partNumber: "15254b", name: "Brick 1×1 with 2 Studs Opposite", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: basicColors, weight: 0.5, keywords: ["SNOT", "dual stud"]),

            // More wheels & tires
            CatalogPiece(partNumber: "92402", name: "Wheel 22mm x 24mm Technic", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 3, heightUnits: 3),
                         commonColors: [.gray, .darkGray], weight: 3.5, keywords: ["technic", "wheel"]),
            CatalogPiece(partNumber: "86652", name: "Tire 30.4 x 14mm", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 3, heightUnits: 3),
                         commonColors: [.black], weight: 4.0, keywords: ["tire", "medium"]),
            CatalogPiece(partNumber: "15413", name: "Wheel Hub 11mm with Axle Hole", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 0.8, keywords: ["hub", "small"]),
            CatalogPiece(partNumber: "44293", name: "Tire 21mm x 9.9mm Offset Tread", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: [.black], weight: 1.5, keywords: ["tire", "offset"]),

            // More minifigure hats and headgear
            CatalogPiece(partNumber: "3629b", name: "Minifigure Hair Short Tousled", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.black, .brown, .yellow], weight: 0.4, keywords: ["hair", "short", "tousled"]),
            CatalogPiece(partNumber: "3625", name: "Minifigure Construction Helmet", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.yellow, .white, .red, .orange], weight: 0.5, keywords: ["helmet", "hard hat", "construction"]),
            CatalogPiece(partNumber: "62711", name: "Minifigure Fire Helmet", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.red, .black, .white], weight: 0.5, keywords: ["helmet", "fire", "firefighter"]),
            CatalogPiece(partNumber: "13768", name: "Minifigure Chef Hat", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.white], weight: 0.5, keywords: ["chef", "hat", "cook"]),
            CatalogPiece(partNumber: "30086", name: "Minifigure Pirate Hat", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: [.black, .brown], weight: 1.0, keywords: ["pirate", "hat", "tricorne"]),
            CatalogPiece(partNumber: "3844", name: "Minifigure Castle Helmet Closed", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.gray, .darkGray, .black, .gray], weight: 1.0, keywords: ["knight", "helmet", "medieval"]),
            CatalogPiece(partNumber: "89520", name: "Minifigure Hair Top Knot", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.black, .brown], weight: 0.5, keywords: ["hair", "top knot", "samurai"]),
            CatalogPiece(partNumber: "11256", name: "Minifigure Crown", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .yellow, .gray], weight: 0.5, keywords: ["crown", "king", "queen"]),

            // More food & accessories
            CatalogPiece(partNumber: "24482", name: "Minifigure Gem", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.transparent, .transparentRed, .transparentBlue, .lime], weight: 0.1, keywords: ["gem", "diamond", "jewel"]),
            CatalogPiece(partNumber: "63462", name: "Minifigure Utensil Goblet", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .gray, .darkGray, .brown], weight: 0.3, keywords: ["goblet", "chalice", "medieval"]),
            CatalogPiece(partNumber: "93552", name: "Food Croissant", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.tan, .brown], weight: 0.2, keywords: ["croissant", "bread", "food"]),
            CatalogPiece(partNumber: "33178", name: "Food Pretzel", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.brown, .tan], weight: 0.2, keywords: ["pretzel", "food"]),
            CatalogPiece(partNumber: "27382", name: "Food Baby Bottle", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.white, .transparent], weight: 0.2, keywords: ["bottle", "baby"]),
            CatalogPiece(partNumber: "6188b", name: "Food Carrot", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.orange], weight: 0.2, keywords: ["carrot", "vegetable", "food"]),
        ]
    }
}
