import Foundation

// MARK: - Extended Catalog Part 5 (Final push to 1,600+ total)
// Fills remaining gaps: windows/doors, wheels/tires, train, fences, containers,
// decorated tiles, modified plates, additional technic, and niche specialty.

extension LegoPartsCatalog {

    func loadExtendedCatalog5() -> [CatalogPiece] {
        let allColors = LegoColor.allCases
        let basicColors: [LegoColor] = [.red, .blue, .yellow, .green, .black, .white, .gray, .darkGray, .orange, .brown, .tan]
        let structuralColors: [LegoColor] = [.black, .gray, .darkGray, .white, .tan, .brown]
        let transColors: [LegoColor] = [.transparent, .transparentBlue, .transparentRed]

        return [

            // ═══════════════════════════════════════════
            // WINDOWS & DOORS - Comprehensive
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "60594", name: "Window 1×2×3 Flat Front", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 9),
                         commonColors: [.white, .gray, .black, .tan], weight: 2.5, keywords: ["flat", "modern"]),
            CatalogPiece(partNumber: "60593", name: "Window Glass 1×2×3", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 9),
                         commonColors: transColors, weight: 1.0, keywords: ["glass", "pane"]),
            CatalogPiece(partNumber: "60596", name: "Window Frame 1×4×6 with 3 Panes", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 18),
                         commonColors: [.white, .gray, .black], weight: 6.0, keywords: ["large", "triple"]),
            CatalogPiece(partNumber: "60603", name: "Window Glass 1×4×6", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 18),
                         commonColors: transColors, weight: 3.0, keywords: ["glass", "large"]),
            CatalogPiece(partNumber: "3853", name: "Window Frame 1×4×3", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 9),
                         commonColors: [.white, .gray, .black, .red], weight: 3.5, keywords: ["frame", "standard"]),
            CatalogPiece(partNumber: "3854", name: "Window Glass 1×4×3", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 9),
                         commonColors: transColors, weight: 1.5, keywords: ["glass"]),
            CatalogPiece(partNumber: "3855", name: "Window Frame 1×4×5 with Fixed Glass", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 15),
                         commonColors: [.white, .gray], weight: 5.0, keywords: ["tall", "fixed"]),
            CatalogPiece(partNumber: "60598", name: "Window Frame 1×4×3 Train", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 9),
                         commonColors: [.white, .black, .gray], weight: 3.5, keywords: ["train", "sliding"]),
            CatalogPiece(partNumber: "4035", name: "Window Frame 2×4×3", category: .window,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 9),
                         commonColors: [.white, .gray, .black], weight: 5.0, keywords: ["deep", "double"]),
            CatalogPiece(partNumber: "60616", name: "Door 1×4×6 with Stud Handle", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 18),
                         commonColors: [.white, .gray, .black, .red, .brown], weight: 5.0, keywords: ["door", "full height"]),
            CatalogPiece(partNumber: "60614", name: "Door Frame 1×4×6", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 18),
                         commonColors: [.white, .gray, .black, .brown], weight: 6.0, keywords: ["frame", "entry"]),
            CatalogPiece(partNumber: "4131", name: "Door Sliding Base", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 6, heightUnits: 5),
                         commonColors: [.white, .gray], weight: 3.0, keywords: ["sliding"]),
            CatalogPiece(partNumber: "93096", name: "Door 1×3×4 Left", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 12),
                         commonColors: [.white, .gray, .black], weight: 3.5, keywords: ["left", "french"]),
            CatalogPiece(partNumber: "93097", name: "Door 1×3×4 Right", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 12),
                         commonColors: [.white, .gray, .black], weight: 3.5, keywords: ["right", "french"]),
            CatalogPiece(partNumber: "60599", name: "Garage Door Rolling Shutter", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 6, heightUnits: 9),
                         commonColors: [.white, .gray, .black], weight: 5.0, keywords: ["garage", "rolling"]),

            // ═══════════════════════════════════════════
            // WHEELS & TIRES - Extended set
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "56145", name: "Wheel 30.4×20 VR", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 3, heightUnits: 3),
                         commonColors: [.gray, .darkGray], weight: 4.0, keywords: ["wheel", "medium"]),
            CatalogPiece(partNumber: "56898", name: "Tire 43.2×22 ZR", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 3, heightUnits: 3),
                         commonColors: [.black], weight: 5.0, keywords: ["tire", "rubber"]),
            CatalogPiece(partNumber: "93593", name: "Wheel 11×6 Motorcycle", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 1.5, keywords: ["motorcycle", "small"]),
            CatalogPiece(partNumber: "6014", name: "Wheel 11×12 Wide", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: [.white, .gray, .darkGray], weight: 2.0, keywords: ["wheel", "wide"]),
            CatalogPiece(partNumber: "6015", name: "Tire 21×12 Smooth", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: [.black], weight: 1.5, keywords: ["tire", "smooth"]),
            CatalogPiece(partNumber: "55982", name: "Wheel 18×14 with Pin Hole", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: [.gray, .darkGray, .black], weight: 3.0, keywords: ["pin hole"]),
            CatalogPiece(partNumber: "56891", name: "Tire 37×18R", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: [.black], weight: 4.0, keywords: ["tire", "racing"]),
            CatalogPiece(partNumber: "2903", name: "Wheel Spoked 2×2", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: [.gray, .gray], weight: 2.0, keywords: ["spoked", "carriage"]),
            CatalogPiece(partNumber: "4624", name: "Wheel Skateboard", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.white, .gray, .darkGray], weight: 0.5, keywords: ["skateboard", "small"]),
            CatalogPiece(partNumber: "30285", name: "Wheel Bicycle", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: [.black, .gray], weight: 2.5, keywords: ["bicycle", "bike"]),
            CatalogPiece(partNumber: "2695", name: "Tire Bicycle", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: [.black], weight: 1.5, keywords: ["bicycle tire"]),

            // ═══════════════════════════════════════════
            // TRAIN PARTS
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "53400", name: "Train Track Straight", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 16, heightUnits: 1),
                         commonColors: [.darkGray], weight: 12.0, keywords: ["train", "track", "rail"]),
            CatalogPiece(partNumber: "53401", name: "Train Track Curved", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 16, heightUnits: 1),
                         commonColors: [.darkGray], weight: 12.0, keywords: ["train", "curve", "rail"]),
            CatalogPiece(partNumber: "53407", name: "Train Track Switch Left", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 16, heightUnits: 1),
                         commonColors: [.darkGray], weight: 20.0, keywords: ["train", "switch", "left"]),
            CatalogPiece(partNumber: "53404", name: "Train Track Switch Right", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 16, heightUnits: 1),
                         commonColors: [.darkGray], weight: 20.0, keywords: ["train", "switch", "right"]),
            CatalogPiece(partNumber: "92088", name: "Train Buffer Beam", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 6, heightUnits: 3),
                         commonColors: [.black, .gray], weight: 6.0, keywords: ["train", "buffer"]),
            CatalogPiece(partNumber: "92089", name: "Train Wheel Holder 2×4", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 2),
                         commonColors: [.black, .darkGray], weight: 5.0, keywords: ["train", "bogie"]),
            CatalogPiece(partNumber: "57878", name: "Train Wheel Pair", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 8.0, keywords: ["train", "wheel"]),
            CatalogPiece(partNumber: "2871", name: "Train Coupling Magnet", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: [.black, .gray], weight: 4.0, keywords: ["train", "coupling", "magnet"]),

            // ═══════════════════════════════════════════
            // FENCES & BARRIERS
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "3633", name: "Fence 1×4×1 Picket", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 3),
                         commonColors: [.white, .brown, .tan], weight: 0.8, keywords: ["fence", "picket"]),
            CatalogPiece(partNumber: "30055", name: "Fence 1×4×2 Ornamental", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 6),
                         commonColors: [.black, .white, .gray], weight: 1.5, keywords: ["fence", "iron"]),
            CatalogPiece(partNumber: "3185", name: "Fence 1×4×2", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 6),
                         commonColors: [.white, .black, .brown, .red], weight: 1.5, keywords: ["fence", "rail"]),
            CatalogPiece(partNumber: "15332", name: "Fence 4×4×2 Quarter Round", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 6),
                         commonColors: [.black, .gray], weight: 3.0, keywords: ["fence", "curved"]),
            CatalogPiece(partNumber: "4083b", name: "Fence 1×4×2 Stockade", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 6),
                         commonColors: [.brown, .brown], weight: 1.5, keywords: ["fence", "stockade", "castle"]),
            CatalogPiece(partNumber: "90195", name: "Bar 1×4×2 Barrier Railing", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 6),
                         commonColors: [.white, .gray, .black], weight: 1.0, keywords: ["railing", "barrier"]),

            // ═══════════════════════════════════════════
            // CONTAINERS & CRATES
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "30150", name: "Container Treasure Chest Bottom", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 3),
                         commonColors: [.brown, .brown, .gray], weight: 3.0, keywords: ["chest", "treasure"]),
            CatalogPiece(partNumber: "30151", name: "Container Treasure Chest Lid", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 2),
                         commonColors: [.brown, .brown, .gray], weight: 2.0, keywords: ["chest", "lid"]),
            CatalogPiece(partNumber: "30109", name: "Container Barrel 2×2×2", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 6),
                         commonColors: [.brown, .brown, .gray], weight: 3.5, keywords: ["barrel", "pirate"]),
            CatalogPiece(partNumber: "61780", name: "Container Crate 3×4×1⅔", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 4, heightUnits: 5),
                         commonColors: [.brown, .brown, .gray], weight: 4.0, keywords: ["crate", "shipping"]),
            CatalogPiece(partNumber: "4345", name: "Container 2×2×2 Open Top", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 6),
                         commonColors: basicColors, weight: 2.5, keywords: ["container", "bin"]),
            CatalogPiece(partNumber: "30075", name: "Container Mailbox 2×2", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 6),
                         commonColors: [.red, .blue, .yellow], weight: 2.5, keywords: ["mailbox", "post"]),
            CatalogPiece(partNumber: "2489", name: "Container Box 2×2", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: basicColors, weight: 1.5, keywords: ["box", "small"]),
            CatalogPiece(partNumber: "6966", name: "Container Cupboard 2×3×2", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 6),
                         commonColors: [.white, .gray, .brown], weight: 4.0, keywords: ["cupboard", "cabinet"]),

            // ═══════════════════════════════════════════
            // BRACKETS - More sizes
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "99781", name: "Bracket 1×2 - 1×2 Down", category: .bracket,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 0.6, keywords: ["bracket", "down"]),
            CatalogPiece(partNumber: "36841", name: "Bracket 1×2 - 1×2 Up", category: .bracket,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 0.6, keywords: ["bracket", "up"]),
            CatalogPiece(partNumber: "44728", name: "Bracket 1×2 - 2×2", category: .bracket,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 1.0, keywords: ["bracket"]),
            CatalogPiece(partNumber: "92411", name: "Bracket 1×2 - 2×4", category: .bracket,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 3),
                         commonColors: structuralColors, weight: 1.5, keywords: ["bracket", "wide"]),
            CatalogPiece(partNumber: "73825", name: "Bracket 2×2 - 2×2 Up", category: .bracket,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 1.2, keywords: ["bracket", "square"]),
            CatalogPiece(partNumber: "21712", name: "Bracket 1×1 - 1×1 Inverted", category: .bracket,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: structuralColors, weight: 0.3, keywords: ["bracket", "tiny"]),

            // ═══════════════════════════════════════════
            // MODIFIED BRICKS - Remaining
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "87087", name: "Brick 1×1 with Stud on Side", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: allColors, weight: 0.5, keywords: ["SNOT", "side stud"]),
            CatalogPiece(partNumber: "47905", name: "Brick 1×1 with Studs on 2 Sides", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: basicColors, weight: 0.5, keywords: ["SNOT", "corner"]),
            CatalogPiece(partNumber: "2877", name: "Brick 1×2 with Grille", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: [.gray, .darkGray, .black, .white], weight: 0.9, keywords: ["grille", "vent"]),
            CatalogPiece(partNumber: "30136", name: "Brick 1×2 Log", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: [.brown, .brown, .tan], weight: 1.0, keywords: ["log", "cabin"]),
            CatalogPiece(partNumber: "30137", name: "Brick 1×4 Log", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 3),
                         commonColors: [.brown, .brown, .tan], weight: 2.0, keywords: ["log", "cabin"]),
            CatalogPiece(partNumber: "2456b", name: "Brick 2×6", category: .brick,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 6, heightUnits: 3),
                         commonColors: allColors, weight: 4.5, keywords: ["standard"]),
            CatalogPiece(partNumber: "3007b", name: "Brick 2×8", category: .brick,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 8, heightUnits: 3),
                         commonColors: allColors, weight: 6.0, keywords: ["standard", "long"]),
            CatalogPiece(partNumber: "3006b", name: "Brick 2×10", category: .brick,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 10, heightUnits: 3),
                         commonColors: basicColors, weight: 8.0, keywords: ["standard", "very long"]),
            CatalogPiece(partNumber: "6112", name: "Brick 1×12", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 12, heightUnits: 3),
                         commonColors: basicColors, weight: 4.0, keywords: ["long"]),
            CatalogPiece(partNumber: "2465", name: "Brick 1×16", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 16, heightUnits: 3),
                         commonColors: basicColors, weight: 5.5, keywords: ["extra long"]),

            // ═══════════════════════════════════════════
            // MODIFIED PLATES - Remaining
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "3794", name: "Plate 1×2 with Centre Stud", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: allColors, weight: 0.3, keywords: ["jumper", "offset"]),
            CatalogPiece(partNumber: "34103", name: "Plate 1×3 Rounded", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 1),
                         commonColors: allColors, weight: 0.5, keywords: ["rounded", "ends"]),
            CatalogPiece(partNumber: "3623b", name: "Plate 1×3", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 1),
                         commonColors: allColors, weight: 0.5, keywords: ["standard"]),
            CatalogPiece(partNumber: "3666b", name: "Plate 1×6", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 6, heightUnits: 1),
                         commonColors: allColors, weight: 1.0, keywords: ["standard"]),
            CatalogPiece(partNumber: "3460b", name: "Plate 1×8", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 8, heightUnits: 1),
                         commonColors: allColors, weight: 1.5, keywords: ["standard"]),
            CatalogPiece(partNumber: "4477b", name: "Plate 1×10", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 10, heightUnits: 1),
                         commonColors: basicColors, weight: 2.0, keywords: ["long"]),
            CatalogPiece(partNumber: "60479b", name: "Plate 1×12", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 12, heightUnits: 1),
                         commonColors: basicColors, weight: 2.5, keywords: ["long"]),
            CatalogPiece(partNumber: "3021b", name: "Plate 2×3", category: .plate,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 1),
                         commonColors: allColors, weight: 1.0, keywords: ["standard"]),
            CatalogPiece(partNumber: "3795b", name: "Plate 2×6", category: .plate,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 6, heightUnits: 1),
                         commonColors: allColors, weight: 2.0, keywords: ["standard"]),
            CatalogPiece(partNumber: "3034b", name: "Plate 2×8", category: .plate,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 8, heightUnits: 1),
                         commonColors: allColors, weight: 3.0, keywords: ["standard"]),
            CatalogPiece(partNumber: "3832", name: "Plate 2×10", category: .plate,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 10, heightUnits: 1),
                         commonColors: basicColors, weight: 3.5, keywords: ["long"]),
            CatalogPiece(partNumber: "2445b", name: "Plate 2×12", category: .plate,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 12, heightUnits: 1),
                         commonColors: basicColors, weight: 4.0, keywords: ["long"]),
            CatalogPiece(partNumber: "91988b", name: "Plate 2×14", category: .plate,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 14, heightUnits: 1),
                         commonColors: basicColors, weight: 5.0, keywords: ["extra long"]),
            CatalogPiece(partNumber: "3029b", name: "Plate 4×12", category: .plate,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 12, heightUnits: 1),
                         commonColors: basicColors, weight: 8.0, keywords: ["large"]),
            CatalogPiece(partNumber: "3030b", name: "Plate 4×10", category: .plate,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 10, heightUnits: 1),
                         commonColors: basicColors, weight: 7.0, keywords: ["large"]),
            CatalogPiece(partNumber: "3035b", name: "Plate 4×8", category: .plate,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 8, heightUnits: 1),
                         commonColors: allColors, weight: 5.0, keywords: ["standard"]),
            CatalogPiece(partNumber: "3958b", name: "Plate 6×6", category: .plate,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 6, heightUnits: 1),
                         commonColors: basicColors, weight: 6.0, keywords: ["square"]),
            CatalogPiece(partNumber: "3033b", name: "Plate 6×10", category: .plate,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 10, heightUnits: 1),
                         commonColors: basicColors, weight: 10.0, keywords: ["large"]),
            CatalogPiece(partNumber: "3456b", name: "Plate 6×14", category: .plate,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 14, heightUnits: 1),
                         commonColors: basicColors, weight: 14.0, keywords: ["extra large"]),
            CatalogPiece(partNumber: "3865b", name: "Plate 8×16", category: .plate,
                         dimensions: PieceDimensions(studsWide: 8, studsLong: 16, heightUnits: 1),
                         commonColors: [.green, .gray, .tan], weight: 20.0, keywords: ["huge"]),

            // ═══════════════════════════════════════════
            // WING PLATES - Remaining
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "3933", name: "Wing Plate 4×8 Right", category: .plate,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 8, heightUnits: 1),
                         commonColors: basicColors, weight: 3.0, keywords: ["wing", "right", "tapered"]),
            CatalogPiece(partNumber: "3934", name: "Wing Plate 4×8 Left", category: .plate,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 8, heightUnits: 1),
                         commonColors: basicColors, weight: 3.0, keywords: ["wing", "left", "tapered"]),
            CatalogPiece(partNumber: "2413", name: "Wing Plate 6×3 Right", category: .plate,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 6, heightUnits: 1),
                         commonColors: basicColors, weight: 2.0, keywords: ["wing", "right"]),
            CatalogPiece(partNumber: "2414", name: "Wing Plate 6×3 Left", category: .plate,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 6, heightUnits: 1),
                         commonColors: basicColors, weight: 2.0, keywords: ["wing", "left"]),

            // ═══════════════════════════════════════════
            // WEDGE - Final variants
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "43710", name: "Wedge 4×2 Triple Right", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 3),
                         commonColors: basicColors, weight: 2.0, keywords: ["wedge", "right"]),
            CatalogPiece(partNumber: "43711", name: "Wedge 4×2 Triple Left", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 3),
                         commonColors: basicColors, weight: 2.0, keywords: ["wedge", "left"]),
            CatalogPiece(partNumber: "43712", name: "Wedge 6×4", category: .slope,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 6, heightUnits: 3),
                         commonColors: basicColors, weight: 4.0, keywords: ["wedge", "large"]),
            CatalogPiece(partNumber: "41747", name: "Wedge 6×2 Right", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 6, heightUnits: 3),
                         commonColors: basicColors, weight: 3.0, keywords: ["wedge", "right"]),
            CatalogPiece(partNumber: "41748", name: "Wedge 6×2 Left", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 6, heightUnits: 3),
                         commonColors: basicColors, weight: 3.0, keywords: ["wedge", "left"]),
            CatalogPiece(partNumber: "47753", name: "Wedge 4×4 No Top Studs", category: .slope,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 3),
                         commonColors: basicColors, weight: 3.0, keywords: ["wedge", "smooth"]),

            // ═══════════════════════════════════════════
            // TECHNIC - Panels & misc
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "87080", name: "Technic Panel Fairing #1", category: .technic,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 7, heightUnits: 1),
                         commonColors: basicColors, weight: 3.0, keywords: ["panel", "fairing"]),
            CatalogPiece(partNumber: "87086", name: "Technic Panel Fairing #2", category: .technic,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 7, heightUnits: 1),
                         commonColors: basicColors, weight: 3.0, keywords: ["panel", "fairing"]),
            CatalogPiece(partNumber: "64391", name: "Technic Panel Fairing #4", category: .technic,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 9, heightUnits: 1),
                         commonColors: basicColors, weight: 4.0, keywords: ["panel", "fairing", "large"]),
            CatalogPiece(partNumber: "64681", name: "Technic Panel Fairing #5", category: .technic,
                         dimensions: PieceDimensions(studsWide: 5, studsLong: 11, heightUnits: 1),
                         commonColors: basicColors, weight: 6.0, keywords: ["panel", "fairing", "extra large"]),
            CatalogPiece(partNumber: "32062", name: "Technic Axle 2 Notched", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: [.red, .black], weight: 0.3, keywords: ["axle", "notched"]),
            CatalogPiece(partNumber: "6536", name: "Technic Axle Joiner Perpendicular", category: .technic,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 1.0, keywords: ["joiner", "perpendicular"]),
            CatalogPiece(partNumber: "48989", name: "Technic Pin Connector Round 2L", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: [.gray, .darkGray, .black], weight: 0.5, keywords: ["connector", "round"]),
            CatalogPiece(partNumber: "32039", name: "Technic Axle Connector with Axle", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 0.8, keywords: ["connector", "axle"]),
            CatalogPiece(partNumber: "60484", name: "Technic Beam 3×3 H-Frame", category: .technic,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 3, heightUnits: 3),
                         commonColors: structuralColors, weight: 3.0, keywords: ["H-frame", "structural"]),
            CatalogPiece(partNumber: "4519", name: "Technic Axle 3", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 1),
                         commonColors: [.gray, .darkGray], weight: 0.3, keywords: ["axle"]),
            CatalogPiece(partNumber: "55013", name: "Technic Axle 8 with Stop", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 8, heightUnits: 1),
                         commonColors: [.black, .darkGray], weight: 1.0, keywords: ["axle", "stop"]),
            CatalogPiece(partNumber: "6587", name: "Technic Axle 3 with Stud", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 1),
                         commonColors: [.gray, .darkGray], weight: 0.4, keywords: ["axle", "stud"]),

            // ═══════════════════════════════════════════
            // INVERTED SLOPES - Remaining
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "3665b", name: "Slope Inverted 45° 1×2", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: allColors, weight: 0.7, keywords: ["inverted", "standard"]),
            CatalogPiece(partNumber: "3747b", name: "Slope Inverted 33° 3×2", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 3),
                         commonColors: allColors, weight: 1.5, keywords: ["inverted", "gentle"]),
            CatalogPiece(partNumber: "4871", name: "Slope Inverted 45° 4×2 Double", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 6),
                         commonColors: basicColors, weight: 3.0, keywords: ["inverted", "double"]),
            CatalogPiece(partNumber: "2341", name: "Slope Inverted 45° 4×4 Double", category: .slope,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 6),
                         commonColors: basicColors, weight: 6.0, keywords: ["inverted", "large"]),
            CatalogPiece(partNumber: "30283", name: "Slope Inverted 45° 1×3", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 3),
                         commonColors: basicColors, weight: 1.0, keywords: ["inverted"]),

            // ═══════════════════════════════════════════
            // MINIFIGURE - Accessories
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "3899", name: "Minifigure Cup", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: allColors, weight: 0.2, keywords: ["cup", "mug"]),
            CatalogPiece(partNumber: "6246", name: "Minifigure Binoculars", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.black, .gray, .darkGray], weight: 0.2, keywords: ["binoculars"]),
            CatalogPiece(partNumber: "88289", name: "Minifigure Camera", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.black, .gray, .white], weight: 0.3, keywords: ["camera", "photo"]),
            CatalogPiece(partNumber: "11402", name: "Minifigure Utensil Wrench", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 0.2, keywords: ["wrench", "tool"]),
            CatalogPiece(partNumber: "4006", name: "Minifigure Shovel", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.gray, .darkGray, .brown], weight: 0.3, keywords: ["shovel", "spade"]),
            CatalogPiece(partNumber: "3836", name: "Minifigure Frying Pan", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .darkGray, .black], weight: 0.3, keywords: ["pan", "cooking"]),
            CatalogPiece(partNumber: "4349", name: "Minifigure Megaphone", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.red, .white, .yellow], weight: 0.2, keywords: ["megaphone", "horn"]),
            CatalogPiece(partNumber: "30089", name: "Minifigure Telescope", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .brown, .gray], weight: 0.3, keywords: ["telescope", "pirate"]),
            CatalogPiece(partNumber: "93552", name: "Minifigure Broom", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.brown, .tan, .yellow], weight: 0.3, keywords: ["broom", "witch"]),
            CatalogPiece(partNumber: "95345", name: "Minifigure Wand", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.brown, .brown, .black], weight: 0.1, keywords: ["wand", "magic"]),
            CatalogPiece(partNumber: "30152", name: "Minifigure Gem Diamond", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.transparent, .transparentBlue, .transparentRed], weight: 0.1, keywords: ["gem", "diamond", "jewel"]),
            CatalogPiece(partNumber: "99563", name: "Minifigure Carrot", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.orange], weight: 0.1, keywords: ["carrot", "food", "vegetable"]),

            // ═══════════════════════════════════════════
            // HINGE - Final remaining
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "44301", name: "Hinge Plate 1×2 Locking Fingers on End", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.4, keywords: ["hinge", "locking"]),
            CatalogPiece(partNumber: "44302b", name: "Hinge Plate 1×2 Locking Fingers on Side", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.4, keywords: ["hinge", "locking", "side"]),
            CatalogPiece(partNumber: "44567", name: "Hinge Plate 1×2 Locking Short Stub", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.4, keywords: ["hinge", "short"]),
            CatalogPiece(partNumber: "44568", name: "Hinge Plate 1×2 Locking Long Stub", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.4, keywords: ["hinge", "long stub"]),
            CatalogPiece(partNumber: "2429", name: "Hinge Plate 1×4 Top", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.6, keywords: ["hinge", "plate"]),
            CatalogPiece(partNumber: "2430", name: "Hinge Plate 1×4 Bottom", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.6, keywords: ["hinge", "plate"]),
            CatalogPiece(partNumber: "6134", name: "Hinge Brick 2×2 with Top Plate", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 1.5, keywords: ["hinge", "brick"]),
            CatalogPiece(partNumber: "30386", name: "Hinge Brick 1×2 with Click Lock on End", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 0.8, keywords: ["hinge", "click"]),

            // ═══════════════════════════════════════════
            // ADDITIONAL MISC SPECIALTY
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "6141", name: "Plate 1×1 Round", category: .round,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: allColors, weight: 0.1, keywords: ["transparent", "light"]),
            CatalogPiece(partNumber: "85861", name: "Plate 1×1 Round with Open Stud", category: .round,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: allColors, weight: 0.1, keywords: ["round", "open"]),
            CatalogPiece(partNumber: "15573", name: "Plate 1×2 with Groove and Stud", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: allColors, weight: 0.3, keywords: ["groove", "rail"]),
            CatalogPiece(partNumber: "32028", name: "Plate 1×2 with Door Rail", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.3, keywords: ["door rail", "groove"]),
            CatalogPiece(partNumber: "99206", name: "Tile 2×3 Pentagonal", category: .tile,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 1),
                         commonColors: basicColors, weight: 0.7, keywords: ["pentagonal", "shield"]),
            CatalogPiece(partNumber: "22388", name: "Tile 1×2 with Stud", category: .tile,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: allColors, weight: 0.3, keywords: ["tile", "stud"]),
            CatalogPiece(partNumber: "11477", name: "Slope Curved 2×1 No Studs", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: allColors, weight: 0.5, keywords: ["curved", "smooth"]),
            CatalogPiece(partNumber: "24246", name: "Slope Curved 3×1", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 2),
                         commonColors: allColors, weight: 0.7, keywords: ["curved"]),
            CatalogPiece(partNumber: "93273", name: "Slope Curved 4×1 Double", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 2),
                         commonColors: allColors, weight: 1.0, keywords: ["curved", "double"]),
            CatalogPiece(partNumber: "61678", name: "Slope Curved 4×1 Inverted", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 2),
                         commonColors: allColors, weight: 1.0, keywords: ["curved", "inverted"]),
            CatalogPiece(partNumber: "93606", name: "Slope Curved 4×2", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 2),
                         commonColors: basicColors, weight: 2.0, keywords: ["curved"]),

            // Final unique parts
            CatalogPiece(partNumber: "92280", name: "Propeller 3 Blade", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 3, heightUnits: 1),
                         commonColors: [.gray, .darkGray, .white, .black], weight: 1.0, keywords: ["propeller", "helicopter"]),
            CatalogPiece(partNumber: "4745", name: "Propeller 4 Blade", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 1),
                         commonColors: [.gray, .darkGray, .white], weight: 2.0, keywords: ["propeller", "airplane"]),
            CatalogPiece(partNumber: "30057", name: "Parabolic Ring", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 3),
                         commonColors: [.gray, .darkGray, .gray], weight: 4.0, keywords: ["parabolic", "satellite"]),
            CatalogPiece(partNumber: "93273b", name: "Wedge Plate 4×2 Right", category: .plate,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 1),
                         commonColors: basicColors, weight: 1.0, keywords: ["wedge", "plate", "right"]),
            CatalogPiece(partNumber: "93274b", name: "Wedge Plate 4×2 Left", category: .plate,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 1),
                         commonColors: basicColors, weight: 1.0, keywords: ["wedge", "plate", "left"]),
            CatalogPiece(partNumber: "4073c", name: "Plate 1×1 Round Transparent", category: .round,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: transColors, weight: 0.1, keywords: ["round", "light", "transparent"]),

            // Staircase and ladder
            CatalogPiece(partNumber: "30134", name: "Staircase 7×4×6", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 7, heightUnits: 18),
                         commonColors: [.brown, .tan, .gray, .white], weight: 12.0, keywords: ["stairs", "staircase"]),
            CatalogPiece(partNumber: "4175", name: "Ladder 3.18 with Side Supports", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 6),
                         commonColors: [.white, .gray, .darkGray], weight: 1.0, keywords: ["ladder", "small"]),
            CatalogPiece(partNumber: "30543", name: "Street Sign Clip on Bar 7×3", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 7, heightUnits: 1),
                         commonColors: [.white, .green, .blue], weight: 0.5, keywords: ["sign", "street"]),

            // Clip parts
            CatalogPiece(partNumber: "48729", name: "Bar Holder with Clip", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: structuralColors, weight: 0.3, keywords: ["clip", "bar holder"]),
            CatalogPiece(partNumber: "11090", name: "Bar Holder with Clip and Stud", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: structuralColors, weight: 0.3, keywords: ["clip", "stud"]),
            CatalogPiece(partNumber: "60470", name: "Plate 1×2 with 2 Open O Clips", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.4, keywords: ["clip", "open"]),

            // Final push: additional slopes and tiles to round out count
            CatalogPiece(partNumber: "3048b", name: "Slope 45° 2×1 Triple", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 9),
                         commonColors: basicColors, weight: 2.0, keywords: ["triple", "tall"]),
            CatalogPiece(partNumber: "3688", name: "Slope 33° 2×4×2 Triple", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 6),
                         commonColors: basicColors, weight: 4.0, keywords: ["triple"]),
            CatalogPiece(partNumber: "2340b", name: "Tail 4×1×3", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 9),
                         commonColors: basicColors, weight: 2.5, keywords: ["tail", "fin", "vertical"]),
            CatalogPiece(partNumber: "6239", name: "Tail 2×3×2 Fin", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 6),
                         commonColors: basicColors, weight: 2.0, keywords: ["tail", "fin"]),
            CatalogPiece(partNumber: "44676", name: "Flag 2×2 Trapezoidal", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: allColors, weight: 0.3, keywords: ["flag", "trapezoid"]),
            CatalogPiece(partNumber: "60471", name: "Hinge Plate 1×2 with Click Lock Double Finger", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.4, keywords: ["hinge", "click", "double"]),
            CatalogPiece(partNumber: "63869", name: "Hinge Plate 1×2 with Click Lock Single Finger on Top", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.4, keywords: ["hinge", "single finger"]),
        ]
    }
}
