import Foundation

// MARK: - Extended Catalog Part 3 (Final batch to reach 1,600+ total)
// Comprehensive coverage of remaining part variants across all categories.

extension LegoPartsCatalog {

    func loadExtendedCatalog3() -> [CatalogPiece] {
        let allColors = LegoColor.allCases
        let basicColors: [LegoColor] = [.red, .blue, .yellow, .green, .black, .white, .gray, .darkGray, .orange, .brown, .tan]
        let structuralColors: [LegoColor] = [.black, .gray, .darkGray, .white, .tan, .brown]
        let brightColors: [LegoColor] = [.red, .blue, .yellow, .green, .orange, .lime, .purple, .pink, .lightBlue]
        let transColors: [LegoColor] = [.transparent, .transparentBlue, .transparentRed]

        return [

            // ═══════════════════════════════════════════
            // BRICKS - Remaining size variants
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "3005b", name: "Brick 1×1 with Bottom Tube", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: allColors, weight: 0.4, keywords: ["basic"]),
            CatalogPiece(partNumber: "30071", name: "Brick 1×1 with Fin", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: basicColors, weight: 0.5, keywords: ["fin", "tooth"]),
            CatalogPiece(partNumber: "47905", name: "Brick 1×1 with Handle", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: basicColors, weight: 0.5, keywords: ["handle"]),
            CatalogPiece(partNumber: "15207", name: "Brick 1×6 with Holes", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 6, heightUnits: 3),
                         commonColors: structuralColors, weight: 2.6, keywords: ["holes", "technic"]),
            CatalogPiece(partNumber: "2453", name: "Brick 1×1×5", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 15),
                         commonColors: [.white, .gray, .black, .brown, .tan], weight: 3.5, keywords: ["pillar", "tall"]),
            CatalogPiece(partNumber: "4589c", name: "Brick 1×1 with Front Stud", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: basicColors, weight: 0.5, keywords: ["front stud", "SNOT"]),
            CatalogPiece(partNumber: "2362", name: "Brick 1×2×3⅓ Curved Top", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 10),
                         commonColors: basicColors, weight: 3.0, keywords: ["curved", "tall"]),

            // Triple/double height bricks
            CatalogPiece(partNumber: "2454", name: "Brick 1×2×5", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 15),
                         commonColors: [.white, .gray, .black], weight: 5.0, keywords: ["tall", "wall"]),
            CatalogPiece(partNumber: "6560", name: "Brick 1×2×3 with Print", category: .brick,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 9),
                         commonColors: basicColors, weight: 3.0, keywords: ["tall"]),
            CatalogPiece(partNumber: "30400", name: "Brick 2×4×3", category: .brick,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 9),
                         commonColors: [.white, .gray, .black, .tan], weight: 10.0, keywords: ["tall"]),

            // ═══════════════════════════════════════════
            // PLATES - All remaining common sizes
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "3028", name: "Plate 6×12", category: .plate,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 12, heightUnits: 1),
                         commonColors: [.white, .gray, .green, .tan], weight: 10.0, keywords: ["large"]),
            CatalogPiece(partNumber: "3497", name: "Plate 6×20", category: .plate,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 20, heightUnits: 1),
                         commonColors: [.gray, .green], weight: 16.0, keywords: ["extra large"]),
            CatalogPiece(partNumber: "91405", name: "Plate 8×8", category: .plate,
                         dimensions: PieceDimensions(studsWide: 8, studsLong: 8, heightUnits: 1),
                         commonColors: [.green, .gray, .tan], weight: 8.5, keywords: ["square", "large"]),
            CatalogPiece(partNumber: "4166", name: "Plate 8×12", category: .plate,
                         dimensions: PieceDimensions(studsWide: 8, studsLong: 12, heightUnits: 1),
                         commonColors: [.green, .gray], weight: 13.0, keywords: ["large"]),
            CatalogPiece(partNumber: "92438b", name: "Plate 8×16", category: .plate,
                         dimensions: PieceDimensions(studsWide: 8, studsLong: 16, heightUnits: 1),
                         commonColors: [.gray, .green, .tan], weight: 17.0, keywords: ["large"]),

            // Modified plates continued
            CatalogPiece(partNumber: "99773", name: "Plate 2×2 with 1 Stud (Jumper)", category: .plate,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: allColors, weight: 0.5, keywords: ["jumper", "offset", "2x2"]),
            CatalogPiece(partNumber: "11212", name: "Plate 3×3", category: .plate,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 3, heightUnits: 1),
                         commonColors: basicColors, weight: 1.2, keywords: ["square"]),
            CatalogPiece(partNumber: "6141b", name: "Plate 1×1 Round Trans Clear", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: transColors, weight: 0.1, keywords: ["transparent", "round"]),
            CatalogPiece(partNumber: "3023b", name: "Plate 1×2 with Bottom Groove", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: allColors, weight: 0.3, keywords: ["groove"]),
            CatalogPiece(partNumber: "88072", name: "Plate 4×12", category: .plate,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 12, heightUnits: 1),
                         commonColors: [.gray, .white, .black], weight: 6.5, keywords: ["long"]),
            CatalogPiece(partNumber: "30261", name: "Plate 1×1 with Tooth Vertical", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.2, keywords: ["tooth", "fin"]),
            CatalogPiece(partNumber: "49668", name: "Plate 1×1 with Tooth Horizontal", category: .plate,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.2, keywords: ["tooth", "horizontal"]),

            // ═══════════════════════════════════════════
            // TILES - More unique shapes
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "35386", name: "Tile 1×2 with Clips", category: .tile,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.5, keywords: ["clip", "sign"]),
            CatalogPiece(partNumber: "23969", name: "Tile 1×1 Heart", category: .tile,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.red, .pink, .white, .purple], weight: 0.1, keywords: ["heart", "love"]),
            CatalogPiece(partNumber: "29120", name: "Tile 1×1 Star", category: .tile,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.yellow, .gray, .white], weight: 0.1, keywords: ["star"]),
            CatalogPiece(partNumber: "27254", name: "Tile 2×2 Inverted", category: .tile,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: allColors, weight: 0.8, keywords: ["inverted", "smooth"]),
            CatalogPiece(partNumber: "90498b", name: "Tile 6×8", category: .tile,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 8, heightUnits: 1),
                         commonColors: [.gray, .green, .tan], weight: 6.5, keywords: ["large", "smooth"]),
            CatalogPiece(partNumber: "48933", name: "Tile 4×4 Round", category: .tile,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 1),
                         commonColors: basicColors, weight: 3.5, keywords: ["round", "large"]),
            CatalogPiece(partNumber: "35787", name: "Tile 2×3 with Studs", category: .tile,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 1),
                         commonColors: basicColors, weight: 0.8, keywords: ["studs", "modified"]),

            // ═══════════════════════════════════════════
            // SLOPES - All remaining variants
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "3048b", name: "Slope 45° 1×2 Triple", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 6),
                         commonColors: basicColors, weight: 1.5, keywords: ["triple", "steep"]),
            CatalogPiece(partNumber: "30363", name: "Slope 18° 4×2", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 2),
                         commonColors: basicColors, weight: 1.5, keywords: ["gentle", "low"]),
            CatalogPiece(partNumber: "47759", name: "Slope Curved 2×1 Inverted", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: basicColors, weight: 0.5, keywords: ["curved", "inverted"]),
            CatalogPiece(partNumber: "30499", name: "Slope 33° 1×2 with Roughened Surface", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: [.gray, .darkGray, .brown], weight: 0.9, keywords: ["rough", "textured"]),
            CatalogPiece(partNumber: "11153", name: "Slope 33° 4×2 Double", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 3),
                         commonColors: basicColors, weight: 3.0, keywords: ["double", "roof"]),
            CatalogPiece(partNumber: "6069b", name: "Slope 45° 4×4 Inverted Double", category: .slope,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 3),
                         commonColors: basicColors, weight: 6.0, keywords: ["inverted", "large"]),
            CatalogPiece(partNumber: "47757", name: "Slope Curved 4×2 Inverted", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 2),
                         commonColors: basicColors, weight: 2.0, keywords: ["curved", "inverted"]),
            CatalogPiece(partNumber: "93604", name: "Slope Curved 8×1", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 8, heightUnits: 2),
                         commonColors: basicColors, weight: 2.0, keywords: ["curved", "extra long"]),
            CatalogPiece(partNumber: "44126", name: "Slope Curved 6×2", category: .slope,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 6, heightUnits: 3),
                         commonColors: basicColors, weight: 3.5, keywords: ["curved", "large"]),
            CatalogPiece(partNumber: "5404", name: "Slope 33° 3×1 Inverted", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 3),
                         commonColors: basicColors, weight: 1.0, keywords: ["inverted"]),
            CatalogPiece(partNumber: "2449", name: "Slope 75° 2×1×3 Inverted", category: .slope,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 9),
                         commonColors: basicColors, weight: 2.0, keywords: ["inverted", "very steep"]),

            // ═══════════════════════════════════════════
            // ROUND / CYLINDER - All remaining variants
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "87580b", name: "Cylinder 1×1 with Axle Hole", category: .round,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: structuralColors, weight: 0.4, keywords: ["cylinder", "axle"]),
            CatalogPiece(partNumber: "6310", name: "Round Plate 4×4 with Hole", category: .round,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 1),
                         commonColors: basicColors, weight: 3.0, keywords: ["round", "hole"]),
            CatalogPiece(partNumber: "85080", name: "Cylinder 2×4×4 with Cutout", category: .round,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 12),
                         commonColors: [.gray, .white, .transparentBlue], weight: 6.0, keywords: ["half", "cockpit"]),
            CatalogPiece(partNumber: "68212", name: "Round Brick 2×2×1 Cone", category: .round,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: basicColors, weight: 1.5, keywords: ["cone", "truncated"]),
            CatalogPiece(partNumber: "3062b", name: "Round Brick 1×1 with Axle Hole", category: .round,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: structuralColors, weight: 0.3, keywords: ["axle", "cylinder"]),
            CatalogPiece(partNumber: "6133", name: "Round Brick 2×2 with Grille", category: .round,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: [.gray, .darkGray], weight: 1.8, keywords: ["grille", "engine"]),
            CatalogPiece(partNumber: "4740b", name: "Dish 2×2 Inverted", category: .round,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: basicColors, weight: 0.5, keywords: ["dish", "inverted"]),
            CatalogPiece(partNumber: "44359", name: "Dish 3×3 Inverted", category: .round,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 3, heightUnits: 1),
                         commonColors: basicColors, weight: 1.5, keywords: ["dish", "inverted"]),
            CatalogPiece(partNumber: "30660", name: "Cone 2×2×2 Open Stud", category: .round,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 6),
                         commonColors: basicColors, weight: 2.0, keywords: ["cone", "open"]),
            CatalogPiece(partNumber: "47408", name: "Dome 6×6×3", category: .round,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 6, heightUnits: 9),
                         commonColors: [.transparent, .white, .gray], weight: 10.0, keywords: ["dome", "large", "observatory"]),

            // ═══════════════════════════════════════════
            // ARCHES - Remaining variants
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "30935", name: "Arch 1×4×1⅓", category: .arch,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 4),
                         commonColors: basicColors, weight: 1.5, keywords: ["low", "arch"]),
            CatalogPiece(partNumber: "6184", name: "Arch 1×8×2", category: .arch,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 8, heightUnits: 6),
                         commonColors: [.white, .gray, .brown], weight: 5.0, keywords: ["wide", "bridge"]),
            CatalogPiece(partNumber: "15254c", name: "Arch 1×5×4 Irregular", category: .arch,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 5, heightUnits: 12),
                         commonColors: [.white, .gray, .brown], weight: 5.0, keywords: ["irregular", "organic"]),
            CatalogPiece(partNumber: "2339b", name: "Arch 1×5×2", category: .arch,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 5, heightUnits: 6),
                         commonColors: basicColors, weight: 3.0, keywords: ["medium"]),
            CatalogPiece(partNumber: "32279", name: "Arch 1×10×2 Thin", category: .arch,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 10, heightUnits: 6),
                         commonColors: [.white, .gray], weight: 5.0, keywords: ["thin", "wide"]),

            // ═══════════════════════════════════════════
            // TECHNIC - Remaining specialty
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "32348", name: "Technic Beam 4×6 Frame", category: .technic,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 6, heightUnits: 3),
                         commonColors: structuralColors, weight: 6.0, keywords: ["frame", "rectangle"]),
            CatalogPiece(partNumber: "32532", name: "Technic Beam 7×5 Triangle", category: .technic,
                         dimensions: PieceDimensions(studsWide: 5, studsLong: 7, heightUnits: 3),
                         commonColors: structuralColors, weight: 5.0, keywords: ["triangle", "truss"]),
            CatalogPiece(partNumber: "2825", name: "Technic Beam 4×4 Cross", category: .technic,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 3),
                         commonColors: structuralColors, weight: 3.0, keywords: ["cross", "plus"]),
            CatalogPiece(partNumber: "40379", name: "Technic Beam 1×3 T-Shape", category: .technic,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 3),
                         commonColors: structuralColors, weight: 1.5, keywords: ["T-shape"]),
            CatalogPiece(partNumber: "32014", name: "Technic Angle Connector #6", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 2),
                         commonColors: [.black, .gray, .darkGray], weight: 0.8, keywords: ["angle", "90 degree"]),
            CatalogPiece(partNumber: "44809", name: "Technic Panel Fairing 3×2", category: .technic,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 3),
                         commonColors: basicColors, weight: 2.0, keywords: ["fairing", "smooth"]),
            CatalogPiece(partNumber: "87086", name: "Technic Pin Connector Round", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.blue, .gray], weight: 0.3, keywords: ["pin", "round"]),
            CatalogPiece(partNumber: "42003", name: "Technic Axle Pin with Studs", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 0.4, keywords: ["axle", "pin", "stud"]),
            CatalogPiece(partNumber: "32291b", name: "Technic Cross Block Double", category: .connector,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 3),
                         commonColors: [.gray, .darkGray], weight: 2.0, keywords: ["cross", "double"]),

            // Technic steering & wheels
            CatalogPiece(partNumber: "32068", name: "Technic Turntable Large", category: .technic,
                         dimensions: PieceDimensions(studsWide: 5, studsLong: 5, heightUnits: 3),
                         commonColors: [.gray, .darkGray, .black], weight: 8.0, keywords: ["turntable", "crane"]),
            CatalogPiece(partNumber: "48452b", name: "Technic Differential", category: .technic,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 5, heightUnits: 3),
                         commonColors: [.darkGray], weight: 6.0, keywords: ["differential", "gear"]),
            CatalogPiece(partNumber: "32494", name: "Technic Bush 1/2 Smooth", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.yellow, .gray, .darkGray], weight: 0.2, keywords: ["bush", "spacer"]),
            CatalogPiece(partNumber: "4265", name: "Technic Bush Half", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.gray, .darkGray], weight: 0.2, keywords: ["bush", "half"]),

            // ═══════════════════════════════════════════
            // WEDGE BRICKS - Remaining
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "43722", name: "Wedge 3×3 Left", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 3, heightUnits: 3),
                         commonColors: basicColors, weight: 3.0, keywords: ["left"]),
            CatalogPiece(partNumber: "43723", name: "Wedge 3×3 Right", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 3, heightUnits: 3),
                         commonColors: basicColors, weight: 3.0, keywords: ["right"]),
            CatalogPiece(partNumber: "50373", name: "Wedge 3×4 with Stud Notches", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 4, heightUnits: 3),
                         commonColors: basicColors, weight: 3.5, keywords: ["notch"]),
            CatalogPiece(partNumber: "43712", name: "Wedge 6×4 Left", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 6, heightUnits: 3),
                         commonColors: basicColors, weight: 6.0, keywords: ["large", "left"]),
            CatalogPiece(partNumber: "43713", name: "Wedge 6×4 Right", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 6, heightUnits: 3),
                         commonColors: basicColors, weight: 6.0, keywords: ["large", "right"]),

            // ═══════════════════════════════════════════
            // BRACKETS - Remaining
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "3956", name: "Bracket 2×2 - 2×2", category: .bracket,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 1.5, keywords: ["SNOT", "shelf"]),
            CatalogPiece(partNumber: "21712", name: "Bracket 1×2 - 2×2 Inverted", category: .bracket,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 1.2, keywords: ["SNOT", "inverted"]),
            CatalogPiece(partNumber: "76766", name: "Bracket 1×2 - 1×2 Rounded", category: .bracket,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 0.8, keywords: ["SNOT", "rounded"]),
            CatalogPiece(partNumber: "92411", name: "Bracket 1×2 - 2×2", category: .bracket,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 1.2, keywords: ["SNOT"]),

            // ═══════════════════════════════════════════
            // WINDOWS & DOORS - Final batch
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "30058", name: "Window 1×4×3 Train", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 9),
                         commonColors: [.transparentBlue, .transparent], weight: 3.0, keywords: ["train", "glass"]),
            CatalogPiece(partNumber: "2377", name: "Window 1×2×2 Classic", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 6),
                         commonColors: [.white, .brown, .black], weight: 1.5, keywords: ["classic"]),
            CatalogPiece(partNumber: "60599", name: "Window 1×2×3 with Open Center", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 9),
                         commonColors: [.white, .black, .brown], weight: 2.0, keywords: ["open"]),
            CatalogPiece(partNumber: "61345", name: "Door Frame 2×4×6", category: .window,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 18),
                         commonColors: [.white, .black, .brown], weight: 8.0, keywords: ["frame", "wide"]),
            CatalogPiece(partNumber: "2634", name: "Window Shutter 1×2×3", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 9),
                         commonColors: [.red, .green, .white, .brown, .blue], weight: 1.5, keywords: ["shutter"]),
            CatalogPiece(partNumber: "4862", name: "Window 1×2×2 Plane", category: .window,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 6),
                         commonColors: [.transparentBlue, .transparent], weight: 0.8, keywords: ["plane", "aircraft"]),

            // ═══════════════════════════════════════════
            // WHEELS & TIRES - Final batch
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "56904", name: "Wheel 18mm Technic", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: [.gray, .darkGray], weight: 2.0, keywords: ["technic"]),
            CatalogPiece(partNumber: "93595", name: "Tire 24mm x 12mm Low Profile", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: [.black], weight: 1.8, keywords: ["tire", "low profile"]),
            CatalogPiece(partNumber: "32019b", name: "Wheel Hub 20mm Technic", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: [.gray, .darkGray], weight: 2.5, keywords: ["hub", "technic"]),
            CatalogPiece(partNumber: "2695", name: "Tire 8mm x 6mm Smooth", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.black, .white], weight: 0.3, keywords: ["tire", "tiny"]),
            CatalogPiece(partNumber: "15038", name: "Wheel 56mm Technic", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 6, heightUnits: 6),
                         commonColors: [.gray, .darkGray], weight: 15.0, keywords: ["large", "technic"]),
            CatalogPiece(partNumber: "88517", name: "Tire 56mm x 28mm Balloon", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 6, studsLong: 6, heightUnits: 6),
                         commonColors: [.black], weight: 18.0, keywords: ["tire", "balloon", "large"]),
            CatalogPiece(partNumber: "50944", name: "Tire 11mm x 6mm", category: .wheel,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.black], weight: 0.5, keywords: ["tire", "small"]),

            // ═══════════════════════════════════════════
            // HINGES - Final variants
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "44567", name: "Hinge Plate 1×2 Locking with 1 Finger on Top", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.5, keywords: ["hinge", "locking"]),
            CatalogPiece(partNumber: "44302b", name: "Hinge Plate 1×2 with 2 Fingers", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.5, keywords: ["hinge"]),
            CatalogPiece(partNumber: "63868b", name: "Hinge Plate 1×2 Locking Horizontal", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.5, keywords: ["hinge", "horizontal"]),
            CatalogPiece(partNumber: "4276", name: "Hinge Plate 1×2 with 3 Fingers on End", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.5, keywords: ["hinge", "3 fingers"]),
            CatalogPiece(partNumber: "4275", name: "Hinge Plate 1×2 with 2 Fingers on End", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.5, keywords: ["hinge", "2 fingers"]),
            CatalogPiece(partNumber: "3149b", name: "Hinge Plate 2×5 with Pin", category: .hinge,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 5, heightUnits: 1),
                         commonColors: structuralColors, weight: 1.5, keywords: ["hinge", "pin"]),

            // ═══════════════════════════════════════════
            // MINIFIGURE - Final batch
            // ═══════════════════════════════════════════

            CatalogPiece(partNumber: "30608", name: "Minifigure Torso with Arms", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 1, heightUnits: 3),
                         commonColors: allColors, weight: 2.0, keywords: ["torso", "assembled"]),
            CatalogPiece(partNumber: "88585", name: "Minifigure Legs Short", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 1, heightUnits: 2),
                         commonColors: allColors, weight: 0.8, keywords: ["legs", "short", "child"]),
            CatalogPiece(partNumber: "24330", name: "Minifigure Legs Medium", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 1, heightUnits: 3),
                         commonColors: allColors, weight: 1.0, keywords: ["legs", "medium", "teen"]),
            CatalogPiece(partNumber: "10696", name: "Minifigure Legs with Hips", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 1, heightUnits: 3),
                         commonColors: basicColors, weight: 1.2, keywords: ["legs", "hips"]),
            CatalogPiece(partNumber: "3626c", name: "Minifigure Head Dual Sided", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.yellow, .brown, .tan], weight: 0.9, keywords: ["head", "dual", "two faces"]),
            CatalogPiece(partNumber: "62810", name: "Minifigure Wizard Hat", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.black, .blue, .purple, .brown], weight: 0.6, keywords: ["wizard", "hat", "pointy"]),
            CatalogPiece(partNumber: "13787", name: "Minifigure Cowboy Hat", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: [.brown, .brown, .tan, .black], weight: 0.6, keywords: ["cowboy", "hat", "western"]),
            CatalogPiece(partNumber: "18835", name: "Minifigure Top Hat", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.black, .darkGray], weight: 0.5, keywords: ["top hat", "formal"]),
            CatalogPiece(partNumber: "30367c", name: "Minifigure Helmet Sport", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: basicColors, weight: 0.5, keywords: ["helmet", "sport", "bike"]),
            CatalogPiece(partNumber: "3844b", name: "Minifigure Castle Helmet with Visor", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.gray, .darkGray, .gray], weight: 1.2, keywords: ["knight", "visor", "medieval"]),
            CatalogPiece(partNumber: "22411", name: "Minifigure Sombrero", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: [.tan, .brown, .red], weight: 0.8, keywords: ["sombrero", "hat"]),
            CatalogPiece(partNumber: "98133", name: "Minifigure Bandana", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.red, .black, .blue, .white], weight: 0.3, keywords: ["bandana", "pirate"]),
            CatalogPiece(partNumber: "3623", name: "Minifigure Hair Female Pigtails", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.black, .brown, .yellow, .red, .orange], weight: 0.5, keywords: ["hair", "pigtails"]),
            CatalogPiece(partNumber: "87991", name: "Minifigure Hair Side Part", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.black, .brown, .darkGray, .yellow], weight: 0.4, keywords: ["hair", "side part"]),
            CatalogPiece(partNumber: "92081", name: "Minifigure Hair Spiked", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.black, .brown, .yellow, .orange], weight: 0.4, keywords: ["hair", "spiked"]),

            // Minifigure weapons & tools continued
            CatalogPiece(partNumber: "88289", name: "Minifigure Weapon Scimitar", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 4),
                         commonColors: [.gray, .gray], weight: 0.4, keywords: ["scimitar", "curved sword"]),
            CatalogPiece(partNumber: "98370", name: "Minifigure Weapon Mace", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.gray, .darkGray, .gray], weight: 0.5, keywords: ["mace", "weapon"]),
            CatalogPiece(partNumber: "64727", name: "Minifigure Tool Magnifying Glass", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .gray, .brown], weight: 0.3, keywords: ["magnifying glass", "detective"]),
            CatalogPiece(partNumber: "58247", name: "Minifigure Weapon Flintlock Pistol", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.brown, .gray, .gray], weight: 0.3, keywords: ["pistol", "gun", "pirate"]),
            CatalogPiece(partNumber: "95344", name: "Minifigure Weapon Trident", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 6),
                         commonColors: [.gray, .gray, .yellow], weight: 0.5, keywords: ["trident", "neptune", "aqua"]),
            CatalogPiece(partNumber: "18395", name: "Minifigure Musical Instrument Guitar", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: [.red, .brown, .black, .white], weight: 0.5, keywords: ["guitar", "music"]),
            CatalogPiece(partNumber: "25893", name: "Minifigure Musical Instrument Saxophone", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.gray, .yellow], weight: 0.4, keywords: ["saxophone", "music"]),
            CatalogPiece(partNumber: "11640", name: "Minifigure Musical Instrument Violin", category: .minifigure,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: [.brown, .brown], weight: 0.5, keywords: ["violin", "music"]),

            // ═══════════════════════════════════════════
            // SPECIALTY - Final remaining items
            // ═══════════════════════════════════════════

            // Street accessories
            CatalogPiece(partNumber: "11374", name: "Telephone", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.black, .white, .red], weight: 0.3, keywords: ["telephone", "phone"]),
            CatalogPiece(partNumber: "73587", name: "Mailbox 2×2", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: [.red, .blue, .white], weight: 1.5, keywords: ["mailbox", "post"]),
            CatalogPiece(partNumber: "2586", name: "Lamp Post 2×2×7", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 21),
                         commonColors: [.black, .darkGray, .gray], weight: 5.0, keywords: ["lamp", "street", "light"]),
            CatalogPiece(partNumber: "2412b", name: "Tile 1×2 Grille with Groove", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: [.gray, .darkGray], weight: 0.4, keywords: ["grille", "vent"]),
            CatalogPiece(partNumber: "95342", name: "Utensil Syringe", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.transparent, .white], weight: 0.3, keywords: ["syringe", "medical"]),
            CatalogPiece(partNumber: "3062c", name: "Light Brick Round 1×1", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: transColors, weight: 0.3, keywords: ["light", "translucent"]),

            // Storage and furniture
            CatalogPiece(partNumber: "4738", name: "Container Treasure Chest Lid", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 2),
                         commonColors: [.brown, .brown], weight: 1.5, keywords: ["chest", "lid"]),
            CatalogPiece(partNumber: "2602", name: "Umbrella", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 3, heightUnits: 4),
                         commonColors: [.red, .blue, .yellow, .white, .orange], weight: 1.0, keywords: ["umbrella", "parasol"]),
            CatalogPiece(partNumber: "93551", name: "Plant Seaweed", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 6),
                         commonColors: [.green, .darkGreen, .lime], weight: 0.5, keywords: ["seaweed", "ocean", "plant"]),
            CatalogPiece(partNumber: "3741b", name: "Plant Grass Stem", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 4),
                         commonColors: [.green, .lime, .darkGreen], weight: 0.2, keywords: ["grass", "plant"]),
            CatalogPiece(partNumber: "2417b", name: "Plant Leaves Cluster", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 2),
                         commonColors: [.green, .lime, .darkGreen], weight: 1.5, keywords: ["leaves", "cluster"]),
            CatalogPiece(partNumber: "2566", name: "Rock Piece 4×4", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 6),
                         commonColors: [.gray, .darkGray, .brown], weight: 8.0, keywords: ["rock", "boulder"]),
            CatalogPiece(partNumber: "6083", name: "Rock Panel 3×8×7 with Arch", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 8, heightUnits: 21),
                         commonColors: [.gray, .darkGray, .brown], weight: 20.0, keywords: ["rock", "cliff", "cave"]),

            // More vehicle parts
            CatalogPiece(partNumber: "98138b", name: "Vehicle Headlight 1×1 Round", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.transparent, .transparentRed, .yellow], weight: 0.1, keywords: ["headlight", "light"]),
            CatalogPiece(partNumber: "50945", name: "Vehicle Windscreen 4×4×1", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 4, studsLong: 4, heightUnits: 3),
                         commonColors: [.transparent, .transparentBlue], weight: 3.0, keywords: ["windscreen", "car"]),
            CatalogPiece(partNumber: "98281", name: "Vehicle Grill 1×2", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: [.gray, .darkGray, .gray], weight: 0.4, keywords: ["grill", "car"]),
            CatalogPiece(partNumber: "4624", name: "Vehicle Steering Stand", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: [.gray, .darkGray, .black], weight: 0.5, keywords: ["steering", "stand"]),
            CatalogPiece(partNumber: "50943", name: "Vehicle Air Scoop", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 3, heightUnits: 2),
                         commonColors: basicColors, weight: 1.0, keywords: ["scoop", "hood", "car"]),
            CatalogPiece(partNumber: "30163", name: "Vehicle Exhaust Pipe", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 0.5, keywords: ["exhaust", "pipe"]),
            CatalogPiece(partNumber: "52038", name: "Vehicle Spoiler 2×4", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 4, heightUnits: 2),
                         commonColors: basicColors, weight: 1.5, keywords: ["spoiler", "car", "wing"]),

            // More unique specialty
            CatalogPiece(partNumber: "3024b", name: "Plate 1×1 with Clip Ring", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.2, keywords: ["ring", "clip"]),
            CatalogPiece(partNumber: "30374b", name: "Bar 4L (Wand)", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 1),
                         commonColors: [.brown, .brown, .black, .tan], weight: 0.3, keywords: ["wand", "magic"]),
            CatalogPiece(partNumber: "60849", name: "Utensil Fishing Rod", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 8),
                         commonColors: [.brown, .gray], weight: 0.5, keywords: ["fishing", "rod"]),
            CatalogPiece(partNumber: "93552b", name: "Utensil Bone", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: [.white, .tan], weight: 0.2, keywords: ["bone", "skeleton"]),
            CatalogPiece(partNumber: "48727", name: "Utensil Telescope", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 3),
                         commonColors: [.brown, .gray, .gray], weight: 0.3, keywords: ["telescope", "spyglass"]),
            CatalogPiece(partNumber: "2561", name: "Animal Plant Corn Cob", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: [.yellow, .green], weight: 0.5, keywords: ["corn", "food", "farm"]),
            CatalogPiece(partNumber: "99784", name: "Flower Plate 1×1 Five Petals", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.red, .yellow, .white, .pink, .purple, .orange], weight: 0.1, keywords: ["flower", "petal"]),
            CatalogPiece(partNumber: "33291", name: "Claw with Clip", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .gray, .darkGray], weight: 0.3, keywords: ["claw", "hook", "clip"]),
            CatalogPiece(partNumber: "6246b", name: "Utensil Binoculars Modern", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.black, .darkGray], weight: 0.3, keywords: ["binoculars"]),
            CatalogPiece(partNumber: "3959c", name: "Utensil Goblet Gold", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .yellow], weight: 0.3, keywords: ["goblet", "gold", "trophy"]),

            // Remaining connector types
            CatalogPiece(partNumber: "24375", name: "Bar 1×3 with Clip", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.3, keywords: ["bar", "clip"]),
            CatalogPiece(partNumber: "48729b", name: "Bar Holder with Clip", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: structuralColors, weight: 0.3, keywords: ["bar", "holder"]),
            CatalogPiece(partNumber: "63082", name: "Brick 1×4 with Groove", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 3),
                         commonColors: structuralColors, weight: 1.5, keywords: ["groove", "rail"]),
            CatalogPiece(partNumber: "92280b", name: "Plate 1×2 with Top Clip", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.5, keywords: ["clip", "top"]),

            // More misc specialty
            CatalogPiece(partNumber: "6097", name: "Castle Tower 3×3×5", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 3, studsLong: 3, heightUnits: 15),
                         commonColors: [.gray, .darkGray, .brown], weight: 10.0, keywords: ["tower", "castle", "turret"]),
            CatalogPiece(partNumber: "33303", name: "Fence Railing 1×4×2", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 4, heightUnits: 6),
                         commonColors: [.white, .black, .gray], weight: 1.2, keywords: ["railing", "balcony"]),
            CatalogPiece(partNumber: "2585", name: "Antenna 1×1", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 6),
                         commonColors: transColors, weight: 0.2, keywords: ["antenna", "aerial"]),
            CatalogPiece(partNumber: "30035", name: "Plate 1×1 with Tooth", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: [.white, .gray], weight: 0.2, keywords: ["tooth", "claw"]),
            CatalogPiece(partNumber: "30162", name: "Brick 2×2 with Pin", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: structuralColors, weight: 2.0, keywords: ["pin", "technic"]),
            CatalogPiece(partNumber: "60607b", name: "Brick 1×1 Round with Flower Edge", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 1),
                         commonColors: brightColors, weight: 0.2, keywords: ["flower", "edge", "decorative"]),

            // More plate shapes
            CatalogPiece(partNumber: "47397", name: "Plate 2×2 with Single Clip", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 1),
                         commonColors: structuralColors, weight: 0.6, keywords: ["clip", "holder"]),
            CatalogPiece(partNumber: "4599", name: "Tap 1×1", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 0.3, keywords: ["tap", "faucet"]),
            CatalogPiece(partNumber: "30359", name: "Brick Round 2×2 Dome Bottom", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 2),
                         commonColors: basicColors, weight: 1.0, keywords: ["dome", "bottom"]),
            CatalogPiece(partNumber: "50231", name: "Wedge 5×6×2 Curved", category: .wedge,
                         dimensions: PieceDimensions(studsWide: 5, studsLong: 6, heightUnits: 6),
                         commonColors: basicColors, weight: 5.0, keywords: ["curved", "large"]),
            CatalogPiece(partNumber: "30602b", name: "Slope 45° 2×2 Printed", category: .specialty,
                         dimensions: PieceDimensions(studsWide: 2, studsLong: 2, heightUnits: 3),
                         commonColors: basicColors, weight: 1.8, keywords: ["printed", "slope"]),

            // Final connectors & misc
            CatalogPiece(partNumber: "32013", name: "Technic Angle Connector #1", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 0.5, keywords: ["angle", "connector"]),
            CatalogPiece(partNumber: "32015", name: "Technic Angle Connector #5", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 0.5, keywords: ["angle", "112.5"]),
            CatalogPiece(partNumber: "32016", name: "Technic Angle Connector #3", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 0.5, keywords: ["angle", "157.5"]),
            CatalogPiece(partNumber: "48092", name: "Technic Pin Connector Plate 1×2×1⅔", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 5),
                         commonColors: structuralColors, weight: 0.8, keywords: ["plate", "pin"]),
            CatalogPiece(partNumber: "3673", name: "Technic Pin without Friction", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 1, heightUnits: 2),
                         commonColors: [.gray, .darkGray], weight: 0.3, keywords: ["pin", "smooth"]),
            CatalogPiece(partNumber: "62462", name: "Technic Pin Connector Round 2L", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 2),
                         commonColors: [.gray, .darkGray, .black], weight: 0.4, keywords: ["round", "connector"]),
            CatalogPiece(partNumber: "75535", name: "Technic Beam 3 with Pin & Axle", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 3, heightUnits: 3),
                         commonColors: [.gray, .darkGray], weight: 1.0, keywords: ["beam", "pin", "axle"]),
            CatalogPiece(partNumber: "32184b", name: "Technic Cross Block with Axle", category: .connector,
                         dimensions: PieceDimensions(studsWide: 1, studsLong: 2, heightUnits: 3),
                         commonColors: [.gray, .darkGray], weight: 1.0, keywords: ["cross", "axle"]),
        ]
    }
}
